# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\GSTtrans.ui'
#
# Created: Sat Jan 12 16:07:50 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GSTtrans(object):
    def setupUi(self, GSTtrans):
        GSTtrans.setObjectName(_fromUtf8("GSTtrans"))
        GSTtrans.resize(1013, 714)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GSTtrans.sizePolicy().hasHeightForWidth())
        GSTtrans.setSizePolicy(sizePolicy)
        GSTtrans.setMinimumSize(QtCore.QSize(650, 550))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        GSTtrans.setPalette(palette)
        GSTtrans.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GSTtrans.setWindowIcon(icon)
        GSTtrans.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(GSTtrans)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.lbl_current_geoid_directory = QtGui.QLabel(self.centralwidget)
        self.lbl_current_geoid_directory.setObjectName(_fromUtf8("lbl_current_geoid_directory"))
        self.gridLayout_20.addWidget(self.lbl_current_geoid_directory, 0, 3, 1, 1)
        self.lbl_geoid_dir_value = QtGui.QLabel(self.centralwidget)
        self.lbl_geoid_dir_value.setObjectName(_fromUtf8("lbl_geoid_dir_value"))
        self.gridLayout_20.addWidget(self.lbl_geoid_dir_value, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem, 0, 7, 1, 1)
        self.lbl_region = QtGui.QLabel(self.centralwidget)
        self.lbl_region.setObjectName(_fromUtf8("lbl_region"))
        self.gridLayout_20.addWidget(self.lbl_region, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem1, 0, 2, 1, 1)
        self.lbl_region_value = QtGui.QLabel(self.centralwidget)
        self.lbl_region_value.setObjectName(_fromUtf8("lbl_region_value"))
        self.gridLayout_20.addWidget(self.lbl_region_value, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_20, 1, 0, 1, 1)
        self.tab_gsttrans = QtGui.QTabWidget(self.centralwidget)
        self.tab_gsttrans.setObjectName(_fromUtf8("tab_gsttrans"))
        self.tab_interactive = QtGui.QWidget()
        self.tab_interactive.setObjectName(_fromUtf8("tab_interactive"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_interactive)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl_input_info = QtGui.QLabel(self.tab_interactive)
        self.lbl_input_info.setObjectName(_fromUtf8("lbl_input_info"))
        self.verticalLayout_2.addWidget(self.lbl_input_info)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lbl_output_info = QtGui.QLabel(self.tab_interactive)
        self.lbl_output_info.setObjectName(_fromUtf8("lbl_output_info"))
        self.verticalLayout_2.addWidget(self.lbl_output_info)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_input_system = QtGui.QLabel(self.tab_interactive)
        self.lbl_input_system.setObjectName(_fromUtf8("lbl_input_system"))
        self.gridLayout_2.addWidget(self.lbl_input_system, 0, 0, 1, 1)
        self.lbl_x_in = QtGui.QLabel(self.tab_interactive)
        self.lbl_x_in.setObjectName(_fromUtf8("lbl_x_in"))
        self.gridLayout_2.addWidget(self.lbl_x_in, 0, 2, 1, 1)
        self.lbl_y_in = QtGui.QLabel(self.tab_interactive)
        self.lbl_y_in.setObjectName(_fromUtf8("lbl_y_in"))
        self.gridLayout_2.addWidget(self.lbl_y_in, 0, 3, 1, 1)
        self.lbl_z_in = QtGui.QLabel(self.tab_interactive)
        self.lbl_z_in.setObjectName(_fromUtf8("lbl_z_in"))
        self.gridLayout_2.addWidget(self.lbl_z_in, 0, 4, 1, 1)
        self.cb_input_system = QtGui.QComboBox(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_input_system.sizePolicy().hasHeightForWidth())
        self.cb_input_system.setSizePolicy(sizePolicy)
        self.cb_input_system.setEditable(True)
        self.cb_input_system.setObjectName(_fromUtf8("cb_input_system"))
        self.gridLayout_2.addWidget(self.cb_input_system, 1, 0, 1, 1)
        self.bt_change_h_in = QtGui.QPushButton(self.tab_interactive)
        self.bt_change_h_in.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt_change_h_in.setObjectName(_fromUtf8("bt_change_h_in"))
        self.gridLayout_2.addWidget(self.bt_change_h_in, 1, 1, 1, 1)
        self.txt_x_in = QtGui.QLineEdit(self.tab_interactive)
        self.txt_x_in.setText(_fromUtf8(""))
        self.txt_x_in.setObjectName(_fromUtf8("txt_x_in"))
        self.gridLayout_2.addWidget(self.txt_x_in, 1, 2, 1, 1)
        self.txt_y_in = QtGui.QLineEdit(self.tab_interactive)
        self.txt_y_in.setObjectName(_fromUtf8("txt_y_in"))
        self.gridLayout_2.addWidget(self.txt_y_in, 1, 3, 1, 1)
        self.txt_z_in = QtGui.QLineEdit(self.tab_interactive)
        self.txt_z_in.setObjectName(_fromUtf8("txt_z_in"))
        self.gridLayout_2.addWidget(self.txt_z_in, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem4 = QtGui.QSpacerItem(761, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.txt_x_out = QtGui.QLineEdit(self.tab_interactive)
        self.txt_x_out.setReadOnly(True)
        self.txt_x_out.setObjectName(_fromUtf8("txt_x_out"))
        self.gridLayout_3.addWidget(self.txt_x_out, 1, 2, 1, 1)
        self.bt_change_h_out = QtGui.QPushButton(self.tab_interactive)
        self.bt_change_h_out.setObjectName(_fromUtf8("bt_change_h_out"))
        self.gridLayout_3.addWidget(self.bt_change_h_out, 1, 1, 1, 1)
        self.txt_y_out = QtGui.QLineEdit(self.tab_interactive)
        self.txt_y_out.setReadOnly(True)
        self.txt_y_out.setObjectName(_fromUtf8("txt_y_out"))
        self.gridLayout_3.addWidget(self.txt_y_out, 1, 3, 1, 1)
        self.cb_output_system = QtGui.QComboBox(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_output_system.sizePolicy().hasHeightForWidth())
        self.cb_output_system.setSizePolicy(sizePolicy)
        self.cb_output_system.setEditable(True)
        self.cb_output_system.setObjectName(_fromUtf8("cb_output_system"))
        self.gridLayout_3.addWidget(self.cb_output_system, 1, 0, 1, 1)
        self.txt_z_out = QtGui.QLineEdit(self.tab_interactive)
        self.txt_z_out.setReadOnly(True)
        self.txt_z_out.setObjectName(_fromUtf8("txt_z_out"))
        self.gridLayout_3.addWidget(self.txt_z_out, 1, 4, 1, 1)
        self.lbl_x_out = QtGui.QLabel(self.tab_interactive)
        self.lbl_x_out.setObjectName(_fromUtf8("lbl_x_out"))
        self.gridLayout_3.addWidget(self.lbl_x_out, 0, 2, 1, 1)
        self.lbl_z_out = QtGui.QLabel(self.tab_interactive)
        self.lbl_z_out.setObjectName(_fromUtf8("lbl_z_out"))
        self.gridLayout_3.addWidget(self.lbl_z_out, 0, 4, 1, 1)
        self.lbl_y_out = QtGui.QLabel(self.tab_interactive)
        self.lbl_y_out.setObjectName(_fromUtf8("lbl_y_out"))
        self.gridLayout_3.addWidget(self.lbl_y_out, 0, 3, 1, 1)
        self.lbl_output_system = QtGui.QLabel(self.tab_interactive)
        self.lbl_output_system.setObjectName(_fromUtf8("lbl_output_system"))
        self.gridLayout_3.addWidget(self.lbl_output_system, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bt_interactive_swap = QtGui.QPushButton(self.tab_interactive)
        self.bt_interactive_swap.setObjectName(_fromUtf8("bt_interactive_swap"))
        self.horizontalLayout_3.addWidget(self.bt_interactive_swap)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gv_map = QtGui.QGraphicsView(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_map.sizePolicy().hasHeightForWidth())
        self.gv_map.setSizePolicy(sizePolicy)
        self.gv_map.setBaseSize(QtCore.QSize(360, 180))
        self.gv_map.setObjectName(_fromUtf8("gv_map"))
        self.horizontalLayout_2.addWidget(self.gv_map)
        self.gridLayout_18.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.bt_zoom_in = QtGui.QPushButton(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_zoom_in.sizePolicy().hasHeightForWidth())
        self.bt_zoom_in.setSizePolicy(sizePolicy)
        self.bt_zoom_in.setObjectName(_fromUtf8("bt_zoom_in"))
        self.gridLayout_19.addWidget(self.bt_zoom_in, 1, 0, 1, 1)
        self.bt_zoom_out = QtGui.QPushButton(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_zoom_out.sizePolicy().hasHeightForWidth())
        self.bt_zoom_out.setSizePolicy(sizePolicy)
        self.bt_zoom_out.setObjectName(_fromUtf8("bt_zoom_out"))
        self.gridLayout_19.addWidget(self.bt_zoom_out, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem7, 1, 1, 1, 1)
        self.chb_zoom_to_point = QtGui.QCheckBox(self.tab_interactive)
        self.chb_zoom_to_point.setChecked(True)
        self.chb_zoom_to_point.setObjectName(_fromUtf8("chb_zoom_to_point"))
        self.gridLayout_19.addWidget(self.chb_zoom_to_point, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_19, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_18)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lbl_geoid_height = QtGui.QLabel(self.tab_interactive)
        self.lbl_geoid_height.setObjectName(_fromUtf8("lbl_geoid_height"))
        self.gridLayout_6.addWidget(self.lbl_geoid_height, 0, 0, 1, 1)
        self.lbl_geoid_name = QtGui.QLabel(self.tab_interactive)
        self.lbl_geoid_name.setObjectName(_fromUtf8("lbl_geoid_name"))
        self.gridLayout_6.addWidget(self.lbl_geoid_name, 0, 1, 1, 1)
        self.txt_geoid_height = QtGui.QLineEdit(self.tab_interactive)
        self.txt_geoid_height.setAcceptDrops(False)
        self.txt_geoid_height.setReadOnly(True)
        self.txt_geoid_height.setObjectName(_fromUtf8("txt_geoid_height"))
        self.gridLayout_6.addWidget(self.txt_geoid_height, 1, 0, 1, 1)
        self.txt_geoid_name = QtGui.QLineEdit(self.tab_interactive)
        self.txt_geoid_name.setEnabled(True)
        self.txt_geoid_name.setAcceptDrops(False)
        self.txt_geoid_name.setReadOnly(True)
        self.txt_geoid_name.setObjectName(_fromUtf8("txt_geoid_name"))
        self.gridLayout_6.addWidget(self.txt_geoid_name, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.chb_show_scale = QtGui.QCheckBox(self.tab_interactive)
        self.chb_show_scale.setObjectName(_fromUtf8("chb_show_scale"))
        self.verticalLayout_4.addWidget(self.chb_show_scale)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.lbl_scale = QtGui.QLabel(self.tab_interactive)
        self.lbl_scale.setObjectName(_fromUtf8("lbl_scale"))
        self.gridLayout_21.addWidget(self.lbl_scale, 0, 0, 1, 1)
        self.lbl_meridian_convergence = QtGui.QLabel(self.tab_interactive)
        self.lbl_meridian_convergence.setObjectName(_fromUtf8("lbl_meridian_convergence"))
        self.gridLayout_21.addWidget(self.lbl_meridian_convergence, 0, 1, 1, 1)
        self.txt_scale = QtGui.QLineEdit(self.tab_interactive)
        self.txt_scale.setEnabled(False)
        self.txt_scale.setAcceptDrops(False)
        self.txt_scale.setReadOnly(True)
        self.txt_scale.setObjectName(_fromUtf8("txt_scale"))
        self.gridLayout_21.addWidget(self.txt_scale, 1, 0, 1, 1)
        self.txt_meridian_convergence = QtGui.QLineEdit(self.tab_interactive)
        self.txt_meridian_convergence.setEnabled(False)
        self.txt_meridian_convergence.setAcceptDrops(False)
        self.txt_meridian_convergence.setReadOnly(True)
        self.txt_meridian_convergence.setObjectName(_fromUtf8("txt_meridian_convergence"))
        self.gridLayout_21.addWidget(self.txt_meridian_convergence, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_21)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.txt_log = QtGui.QTextEdit(self.tab_interactive)
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.horizontalLayout.addWidget(self.txt_log)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tab_gsttrans.addTab(self.tab_interactive, _fromUtf8(""))
        self.tab_ogr = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ogr.sizePolicy().hasHeightForWidth())
        self.tab_ogr.setSizePolicy(sizePolicy)
        self.tab_ogr.setObjectName(_fromUtf8("tab_ogr"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_ogr)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setBaseSize(QtCore.QSize(0, 24))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.rdobt_f2f_ogr = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_ogr.setChecked(True)
        self.rdobt_f2f_ogr.setObjectName(_fromUtf8("rdobt_f2f_ogr"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_ogr)
        self.rdobt_f2f_simple_text = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_simple_text.setObjectName(_fromUtf8("rdobt_f2f_simple_text"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_simple_text)
        self.rdobt_f2f_dsfl = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_dsfl.setObjectName(_fromUtf8("rdobt_f2f_dsfl"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_dsfl)
        self.rdobt_f2f_kmsformat = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_kmsformat.setObjectName(_fromUtf8("rdobt_f2f_kmsformat"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_kmsformat)
        self.bt_f2f_settings = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_settings.sizePolicy().hasHeightForWidth())
        self.bt_f2f_settings.setSizePolicy(sizePolicy)
        self.bt_f2f_settings.setObjectName(_fromUtf8("bt_f2f_settings"))
        self.horizontalLayout_9.addWidget(self.bt_f2f_settings)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_f2f_input_file = QtGui.QLabel(self.groupBox_3)
        self.lbl_f2f_input_file.setObjectName(_fromUtf8("lbl_f2f_input_file"))
        self.horizontalLayout_5.addWidget(self.lbl_f2f_input_file)
        self.txt_f2f_input_file = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_f2f_input_file.sizePolicy().hasHeightForWidth())
        self.txt_f2f_input_file.setSizePolicy(sizePolicy)
        self.txt_f2f_input_file.setSizeIncrement(QtCore.QSize(0, 0))
        self.txt_f2f_input_file.setObjectName(_fromUtf8("txt_f2f_input_file"))
        self.horizontalLayout_5.addWidget(self.txt_f2f_input_file)
        self.bt_f2f_browse_input = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_browse_input.sizePolicy().hasHeightForWidth())
        self.bt_f2f_browse_input.setSizePolicy(sizePolicy)
        self.bt_f2f_browse_input.setObjectName(_fromUtf8("bt_f2f_browse_input"))
        self.horizontalLayout_5.addWidget(self.bt_f2f_browse_input)
        self.bt_f2f_browse_input_dir = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_browse_input_dir.sizePolicy().hasHeightForWidth())
        self.bt_f2f_browse_input_dir.setSizePolicy(sizePolicy)
        self.bt_f2f_browse_input_dir.setObjectName(_fromUtf8("bt_f2f_browse_input_dir"))
        self.horizontalLayout_5.addWidget(self.bt_f2f_browse_input_dir)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.chb_f2f_all_layers = QtGui.QCheckBox(self.groupBox_3)
        self.chb_f2f_all_layers.setChecked(True)
        self.chb_f2f_all_layers.setObjectName(_fromUtf8("chb_f2f_all_layers"))
        self.horizontalLayout_12.addWidget(self.chb_f2f_all_layers)
        self.txt_f2f_layers_in = QtGui.QLineEdit(self.groupBox_3)
        self.txt_f2f_layers_in.setObjectName(_fromUtf8("txt_f2f_layers_in"))
        self.horizontalLayout_12.addWidget(self.txt_f2f_layers_in)
        self.bt_f2f_input_layers = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_input_layers.sizePolicy().hasHeightForWidth())
        self.bt_f2f_input_layers.setSizePolicy(sizePolicy)
        self.bt_f2f_input_layers.setObjectName(_fromUtf8("bt_f2f_input_layers"))
        self.horizontalLayout_12.addWidget(self.bt_f2f_input_layers)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_ogr)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_f2f_ogrdriver = QtGui.QLabel(self.groupBox_4)
        self.lbl_f2f_ogrdriver.setObjectName(_fromUtf8("lbl_f2f_ogrdriver"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_f2f_ogrdriver)
        self.cb_f2f_ogr_driver = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_f2f_ogr_driver.sizePolicy().hasHeightForWidth())
        self.cb_f2f_ogr_driver.setSizePolicy(sizePolicy)
        self.cb_f2f_ogr_driver.setObjectName(_fromUtf8("cb_f2f_ogr_driver"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_f2f_ogr_driver)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lbl_f2f_output_file = QtGui.QLabel(self.groupBox_4)
        self.lbl_f2f_output_file.setObjectName(_fromUtf8("lbl_f2f_output_file"))
        self.horizontalLayout_6.addWidget(self.lbl_f2f_output_file)
        self.txt_f2f_output_file = QtGui.QLineEdit(self.groupBox_4)
        self.txt_f2f_output_file.setObjectName(_fromUtf8("txt_f2f_output_file"))
        self.horizontalLayout_6.addWidget(self.txt_f2f_output_file)
        self.bt_f2f_browse_output = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_browse_output.sizePolicy().hasHeightForWidth())
        self.bt_f2f_browse_output.setSizePolicy(sizePolicy)
        self.bt_f2f_browse_output.setObjectName(_fromUtf8("bt_f2f_browse_output"))
        self.horizontalLayout_6.addWidget(self.bt_f2f_browse_output)
        self.bt_f2f_browse_output_dir = QtGui.QPushButton(self.groupBox_4)
        self.bt_f2f_browse_output_dir.setObjectName(_fromUtf8("bt_f2f_browse_output_dir"))
        self.horizontalLayout_6.addWidget(self.bt_f2f_browse_output_dir)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chb_f2f_use_log = QtGui.QCheckBox(self.tab_ogr)
        self.chb_f2f_use_log.setChecked(False)
        self.chb_f2f_use_log.setTristate(False)
        self.chb_f2f_use_log.setObjectName(_fromUtf8("chb_f2f_use_log"))
        self.horizontalLayout_11.addWidget(self.chb_f2f_use_log)
        self.chb_f2f_verbose = QtGui.QCheckBox(self.tab_ogr)
        self.chb_f2f_verbose.setChecked(False)
        self.chb_f2f_verbose.setObjectName(_fromUtf8("chb_f2f_verbose"))
        self.horizontalLayout_11.addWidget(self.chb_f2f_verbose)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.txt_f2f_log_name = QtGui.QLineEdit(self.tab_ogr)
        self.txt_f2f_log_name.setEnabled(False)
        self.txt_f2f_log_name.setObjectName(_fromUtf8("txt_f2f_log_name"))
        self.horizontalLayout_11.addWidget(self.txt_f2f_log_name)
        self.bt_f2f_browse_log = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_browse_log.setObjectName(_fromUtf8("bt_f2f_browse_log"))
        self.horizontalLayout_11.addWidget(self.bt_f2f_browse_log)
        spacerItem15 = QtGui.QSpacerItem(170, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.lbl_f2f_input_info = QtGui.QLabel(self.groupBox_2)
        self.lbl_f2f_input_info.setObjectName(_fromUtf8("lbl_f2f_input_info"))
        self.verticalLayout_12.addWidget(self.lbl_f2f_input_info)
        self.lbl_f2f_output_info = QtGui.QLabel(self.groupBox_2)
        self.lbl_f2f_output_info.setObjectName(_fromUtf8("lbl_f2f_output_info"))
        self.verticalLayout_12.addWidget(self.lbl_f2f_output_info)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chb_f2f_label_in_file = QtGui.QCheckBox(self.groupBox_2)
        self.chb_f2f_label_in_file.setObjectName(_fromUtf8("chb_f2f_label_in_file"))
        self.horizontalLayout_10.addWidget(self.chb_f2f_label_in_file)
        self.chb_f2f_set_projection = QtGui.QCheckBox(self.groupBox_2)
        self.chb_f2f_set_projection.setChecked(True)
        self.chb_f2f_set_projection.setObjectName(_fromUtf8("chb_f2f_set_projection"))
        self.horizontalLayout_10.addWidget(self.chb_f2f_set_projection)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        spacerItem17 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.cb_f2f_input_system = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_f2f_input_system.sizePolicy().hasHeightForWidth())
        self.cb_f2f_input_system.setSizePolicy(sizePolicy)
        self.cb_f2f_input_system.setMinimumSize(QtCore.QSize(0, 20))
        self.cb_f2f_input_system.setEditable(True)
        self.cb_f2f_input_system.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_f2f_input_system.setObjectName(_fromUtf8("cb_f2f_input_system"))
        self.horizontalLayout_8.addWidget(self.cb_f2f_input_system)
        self.bt_f2f_change_h_in = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_change_h_in.sizePolicy().hasHeightForWidth())
        self.bt_f2f_change_h_in.setSizePolicy(sizePolicy)
        self.bt_f2f_change_h_in.setMinimumSize(QtCore.QSize(0, 23))
        self.bt_f2f_change_h_in.setObjectName(_fromUtf8("bt_f2f_change_h_in"))
        self.horizontalLayout_8.addWidget(self.bt_f2f_change_h_in)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.cb_f2f_output_system = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_f2f_output_system.sizePolicy().hasHeightForWidth())
        self.cb_f2f_output_system.setSizePolicy(sizePolicy)
        self.cb_f2f_output_system.setMinimumSize(QtCore.QSize(0, 20))
        self.cb_f2f_output_system.setEditable(True)
        self.cb_f2f_output_system.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_f2f_output_system.setObjectName(_fromUtf8("cb_f2f_output_system"))
        self.horizontalLayout_8.addWidget(self.cb_f2f_output_system)
        self.bt_f2f_change_h_out = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_change_h_out.sizePolicy().hasHeightForWidth())
        self.bt_f2f_change_h_out.setSizePolicy(sizePolicy)
        self.bt_f2f_change_h_out.setMinimumSize(QtCore.QSize(0, 23))
        self.bt_f2f_change_h_out.setObjectName(_fromUtf8("bt_f2f_change_h_out"))
        self.horizontalLayout_8.addWidget(self.bt_f2f_change_h_out)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        self.txt_f2f_log = QtGui.QTextEdit(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_f2f_log.sizePolicy().hasHeightForWidth())
        self.txt_f2f_log.setSizePolicy(sizePolicy)
        self.txt_f2f_log.setMaximumSize(QtCore.QSize(16777215, 132))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(9)
        self.txt_f2f_log.setFont(font)
        self.txt_f2f_log.setReadOnly(True)
        self.txt_f2f_log.setObjectName(_fromUtf8("txt_f2f_log"))
        self.verticalLayout_5.addWidget(self.txt_f2f_log)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bt_f2f_execute = QtGui.QPushButton(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_execute.sizePolicy().hasHeightForWidth())
        self.bt_f2f_execute.setSizePolicy(sizePolicy)
        self.bt_f2f_execute.setObjectName(_fromUtf8("bt_f2f_execute"))
        self.gridLayout.addWidget(self.bt_f2f_execute, 0, 0, 1, 1)
        self.bt_f2f_view_output = QtGui.QPushButton(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_view_output.sizePolicy().hasHeightForWidth())
        self.bt_f2f_view_output.setSizePolicy(sizePolicy)
        self.bt_f2f_view_output.setObjectName(_fromUtf8("bt_f2f_view_output"))
        self.gridLayout.addWidget(self.bt_f2f_view_output, 0, 1, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 4, 1, 1)
        self.bt_f2f_view_log = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_view_log.setObjectName(_fromUtf8("bt_f2f_view_log"))
        self.gridLayout.addWidget(self.bt_f2f_view_log, 0, 2, 1, 1)
        self.bt_f2f_clear_log = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_clear_log.setObjectName(_fromUtf8("bt_f2f_clear_log"))
        self.gridLayout.addWidget(self.bt_f2f_clear_log, 0, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.tab_gsttrans.addTab(self.tab_ogr, _fromUtf8(""))
        self.tab_utilities = QtGui.QWidget()
        self.tab_utilities.setObjectName(_fromUtf8("tab_utilities"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_utilities)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gb_bshlm = QtGui.QGroupBox(self.tab_utilities)
        self.gb_bshlm.setObjectName(_fromUtf8("gb_bshlm"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gb_bshlm)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem20)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_10 = QtGui.QLabel(self.gb_bshlm)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_16.addWidget(self.label_10, 0, 0, 1, 1)
        self.lbl_bshlm_description = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_description.setObjectName(_fromUtf8("lbl_bshlm_description"))
        self.gridLayout_16.addWidget(self.lbl_bshlm_description, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_16)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem21)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_2 = QtGui.QLabel(self.gb_bshlm)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_13.addWidget(self.label_2, 2, 1, 1, 1)
        self.cb_bshlm_system = QtGui.QComboBox(self.gb_bshlm)
        self.cb_bshlm_system.setEditable(True)
        self.cb_bshlm_system.setObjectName(_fromUtf8("cb_bshlm_system"))
        self.gridLayout_13.addWidget(self.cb_bshlm_system, 2, 2, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem22, 2, 6, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_13)
        self.chb_bshlm_custom_ellipsoid = QtGui.QCheckBox(self.gb_bshlm)
        self.chb_bshlm_custom_ellipsoid.setEnabled(True)
        self.chb_bshlm_custom_ellipsoid.setObjectName(_fromUtf8("chb_bshlm_custom_ellipsoid"))
        self.verticalLayout_6.addWidget(self.chb_bshlm_custom_ellipsoid)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem23)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lbl_bshlm_ellipsoid = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_ellipsoid.setObjectName(_fromUtf8("lbl_bshlm_ellipsoid"))
        self.gridLayout_15.addWidget(self.lbl_bshlm_ellipsoid, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gb_bshlm)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_15.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gb_bshlm)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_15.addWidget(self.label_11, 1, 1, 1, 1)
        self.txt_bshlm_ellipsoid = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_ellipsoid.setEnabled(False)
        self.txt_bshlm_ellipsoid.setReadOnly(False)
        self.txt_bshlm_ellipsoid.setObjectName(_fromUtf8("txt_bshlm_ellipsoid"))
        self.gridLayout_15.addWidget(self.txt_bshlm_ellipsoid, 2, 0, 1, 1)
        self.txt_bshlm_flattening = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_flattening.setEnabled(False)
        self.txt_bshlm_flattening.setReadOnly(False)
        self.txt_bshlm_flattening.setObjectName(_fromUtf8("txt_bshlm_flattening"))
        self.gridLayout_15.addWidget(self.txt_bshlm_flattening, 2, 2, 1, 1)
        self.txt_bshlm_axis = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_axis.setEnabled(False)
        self.txt_bshlm_axis.setReadOnly(False)
        self.txt_bshlm_axis.setObjectName(_fromUtf8("txt_bshlm_axis"))
        self.gridLayout_15.addWidget(self.txt_bshlm_axis, 2, 1, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem24, 1, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_15)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem25)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txt_bshlm_x1 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_x1.setObjectName(_fromUtf8("txt_bshlm_x1"))
        self.gridLayout_8.addWidget(self.txt_bshlm_x1, 1, 2, 1, 1)
        self.txt_bshlm_y1 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_y1.setObjectName(_fromUtf8("txt_bshlm_y1"))
        self.gridLayout_8.addWidget(self.txt_bshlm_y1, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.gb_bshlm)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 0, 1, 1, 1)
        self.lbl_bshlm_x = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_x.setObjectName(_fromUtf8("lbl_bshlm_x"))
        self.gridLayout_8.addWidget(self.lbl_bshlm_x, 0, 2, 1, 1)
        self.lbl_bshlm_y = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_y.setObjectName(_fromUtf8("lbl_bshlm_y"))
        self.gridLayout_8.addWidget(self.lbl_bshlm_y, 0, 3, 1, 1)
        self.lbl_bshlm_station1 = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_station1.setObjectName(_fromUtf8("lbl_bshlm_station1"))
        self.gridLayout_8.addWidget(self.lbl_bshlm_station1, 1, 0, 1, 1)
        self.lbl_bshlm_station2 = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_station2.setObjectName(_fromUtf8("lbl_bshlm_station2"))
        self.gridLayout_8.addWidget(self.lbl_bshlm_station2, 2, 0, 1, 1)
        self.txt_bshlm_x2 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_x2.setObjectName(_fromUtf8("txt_bshlm_x2"))
        self.gridLayout_8.addWidget(self.txt_bshlm_x2, 2, 2, 1, 1)
        self.txt_bshlm_y2 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_y2.setObjectName(_fromUtf8("txt_bshlm_y2"))
        self.gridLayout_8.addWidget(self.txt_bshlm_y2, 2, 3, 1, 1)
        self.txt_bshlm_lon1 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_lon1.setEnabled(False)
        self.txt_bshlm_lon1.setReadOnly(True)
        self.txt_bshlm_lon1.setObjectName(_fromUtf8("txt_bshlm_lon1"))
        self.gridLayout_8.addWidget(self.txt_bshlm_lon1, 1, 4, 1, 1)
        self.txt_bshlm_lat1 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_lat1.setEnabled(False)
        self.txt_bshlm_lat1.setReadOnly(True)
        self.txt_bshlm_lat1.setObjectName(_fromUtf8("txt_bshlm_lat1"))
        self.gridLayout_8.addWidget(self.txt_bshlm_lat1, 1, 5, 1, 1)
        self.txt_bshlm_lon2 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_lon2.setEnabled(False)
        self.txt_bshlm_lon2.setReadOnly(True)
        self.txt_bshlm_lon2.setObjectName(_fromUtf8("txt_bshlm_lon2"))
        self.gridLayout_8.addWidget(self.txt_bshlm_lon2, 2, 4, 1, 1)
        self.txt_bshlm_lat2 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_lat2.setEnabled(False)
        self.txt_bshlm_lat2.setReadOnly(True)
        self.txt_bshlm_lat2.setObjectName(_fromUtf8("txt_bshlm_lat2"))
        self.gridLayout_8.addWidget(self.txt_bshlm_lat2, 2, 5, 1, 1)
        self.lbl_bshlm_lon = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_lon.setObjectName(_fromUtf8("lbl_bshlm_lon"))
        self.gridLayout_8.addWidget(self.lbl_bshlm_lon, 0, 4, 1, 1)
        self.lbl_bshlm_lat = QtGui.QLabel(self.gb_bshlm)
        self.lbl_bshlm_lat.setObjectName(_fromUtf8("lbl_bshlm_lat"))
        self.gridLayout_8.addWidget(self.lbl_bshlm_lat, 0, 5, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_8)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem26)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.txt_bshlm_distance = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_distance.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_bshlm_distance.sizePolicy().hasHeightForWidth())
        self.txt_bshlm_distance.setSizePolicy(sizePolicy)
        self.txt_bshlm_distance.setObjectName(_fromUtf8("txt_bshlm_distance"))
        self.gridLayout_9.addWidget(self.txt_bshlm_distance, 0, 1, 1, 1)
        self.txt_bshlm_azimuth1 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_azimuth1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_bshlm_azimuth1.sizePolicy().hasHeightForWidth())
        self.txt_bshlm_azimuth1.setSizePolicy(sizePolicy)
        self.txt_bshlm_azimuth1.setObjectName(_fromUtf8("txt_bshlm_azimuth1"))
        self.gridLayout_9.addWidget(self.txt_bshlm_azimuth1, 1, 1, 1, 1)
        self.txt_bshlm_azimuth2 = QtGui.QLineEdit(self.gb_bshlm)
        self.txt_bshlm_azimuth2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_bshlm_azimuth2.sizePolicy().hasHeightForWidth())
        self.txt_bshlm_azimuth2.setSizePolicy(sizePolicy)
        self.txt_bshlm_azimuth2.setObjectName(_fromUtf8("txt_bshlm_azimuth2"))
        self.gridLayout_9.addWidget(self.txt_bshlm_azimuth2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gb_bshlm)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gb_bshlm)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gb_bshlm)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_9.addWidget(self.label_7, 2, 0, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem27, 0, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_9)
        self.txt_bshlm_log = QtGui.QTextEdit(self.gb_bshlm)
        self.txt_bshlm_log.setReadOnly(True)
        self.txt_bshlm_log.setObjectName(_fromUtf8("txt_bshlm_log"))
        self.horizontalLayout_4.addWidget(self.txt_bshlm_log)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem28)
        self.groupBox_6 = QtGui.QGroupBox(self.gb_bshlm)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.rdobt_bshlm_mode1 = QtGui.QRadioButton(self.groupBox_6)
        self.rdobt_bshlm_mode1.setChecked(True)
        self.rdobt_bshlm_mode1.setObjectName(_fromUtf8("rdobt_bshlm_mode1"))
        self.verticalLayout_9.addWidget(self.rdobt_bshlm_mode1)
        self.rdobt_bshlm_mode2 = QtGui.QRadioButton(self.groupBox_6)
        self.rdobt_bshlm_mode2.setObjectName(_fromUtf8("rdobt_bshlm_mode2"))
        self.verticalLayout_9.addWidget(self.rdobt_bshlm_mode2)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem29)
        self.verticalLayout_7.addWidget(self.gb_bshlm)
        self.tab_gsttrans.addTab(self.tab_utilities, _fromUtf8(""))
        self.tab_python = QtGui.QWidget()
        self.tab_python.setObjectName(_fromUtf8("tab_python"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_python)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.txt_python_out = QtGui.QTextEdit(self.tab_python)
        self.txt_python_out.setReadOnly(True)
        self.txt_python_out.setObjectName(_fromUtf8("txt_python_out"))
        self.verticalLayout_11.addWidget(self.txt_python_out)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.bt_python_run = QtGui.QPushButton(self.tab_python)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_python_run.sizePolicy().hasHeightForWidth())
        self.bt_python_run.setSizePolicy(sizePolicy)
        self.bt_python_run.setObjectName(_fromUtf8("bt_python_run"))
        self.horizontalLayout_7.addWidget(self.bt_python_run)
        self.bt_python_load = QtGui.QPushButton(self.tab_python)
        self.bt_python_load.setObjectName(_fromUtf8("bt_python_load"))
        self.horizontalLayout_7.addWidget(self.bt_python_load)
        self.chb_python_process_enter = QtGui.QCheckBox(self.tab_python)
        self.chb_python_process_enter.setChecked(True)
        self.chb_python_process_enter.setObjectName(_fromUtf8("chb_python_process_enter"))
        self.horizontalLayout_7.addWidget(self.chb_python_process_enter)
        self.chb_python_clear = QtGui.QCheckBox(self.tab_python)
        self.chb_python_clear.setChecked(True)
        self.chb_python_clear.setObjectName(_fromUtf8("chb_python_clear"))
        self.horizontalLayout_7.addWidget(self.chb_python_clear)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem30)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.tab_gsttrans.addTab(self.tab_python, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tab_gsttrans, 0, 0, 1, 1)
        GSTtrans.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GSTtrans)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuRegion = QtGui.QMenu(self.menuSettings)
        self.menuRegion.setObjectName(_fromUtf8("menuRegion"))
        self.menuAngular_units = QtGui.QMenu(self.menuSettings)
        self.menuAngular_units.setObjectName(_fromUtf8("menuAngular_units"))
        self.menuAngular_units_derived_output = QtGui.QMenu(self.menuSettings)
        self.menuAngular_units_derived_output.setObjectName(_fromUtf8("menuAngular_units_derived_output"))
        GSTtrans.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GSTtrans)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        GSTtrans.setStatusBar(self.statusbar)
        self.actionNew_KMSTrans = QtGui.QAction(GSTtrans)
        self.actionNew_KMSTrans.setObjectName(_fromUtf8("actionNew_KMSTrans"))
        self.actionAbout_KMSTrans = QtGui.QAction(GSTtrans)
        self.actionAbout_KMSTrans.setObjectName(_fromUtf8("actionAbout_KMSTrans"))
        self.actionHelp = QtGui.QAction(GSTtrans)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionDK = QtGui.QAction(GSTtrans)
        self.actionDK.setObjectName(_fromUtf8("actionDK"))
        self.actionFO = QtGui.QAction(GSTtrans)
        self.actionFO.setObjectName(_fromUtf8("actionFO"))
        self.actionGR = QtGui.QAction(GSTtrans)
        self.actionGR.setObjectName(_fromUtf8("actionGR"))
        self.actionWorld = QtGui.QAction(GSTtrans)
        self.actionWorld.setObjectName(_fromUtf8("actionWorld"))
        self.actionDegrees = QtGui.QAction(GSTtrans)
        self.actionDegrees.setCheckable(True)
        self.actionDegrees.setObjectName(_fromUtf8("actionDegrees"))
        self.actionRadians = QtGui.QAction(GSTtrans)
        self.actionRadians.setCheckable(True)
        self.actionRadians.setObjectName(_fromUtf8("actionRadians"))
        self.actionSx = QtGui.QAction(GSTtrans)
        self.actionSx.setCheckable(True)
        self.actionSx.setObjectName(_fromUtf8("actionSx"))
        self.actionNt = QtGui.QAction(GSTtrans)
        self.actionNt.setCheckable(True)
        self.actionNt.setAutoRepeat(True)
        self.actionNt.setObjectName(_fromUtf8("actionNt"))
        self.actionGeoid_directory = QtGui.QAction(GSTtrans)
        self.actionGeoid_directory.setObjectName(_fromUtf8("actionGeoid_directory"))
        self.actionStation_names_in_input = QtGui.QAction(GSTtrans)
        self.actionStation_names_in_input.setCheckable(True)
        self.actionStation_names_in_input.setObjectName(_fromUtf8("actionStation_names_in_input"))
        self.actionStation_names_in_output = QtGui.QAction(GSTtrans)
        self.actionStation_names_in_output.setCheckable(True)
        self.actionStation_names_in_output.setEnabled(False)
        self.actionStation_names_in_output.setObjectName(_fromUtf8("actionStation_names_in_output"))
        self.actionVerbose_output = QtGui.QAction(GSTtrans)
        self.actionVerbose_output.setCheckable(True)
        self.actionVerbose_output.setChecked(True)
        self.actionVerbose_output.setObjectName(_fromUtf8("actionVerbose_output"))
        self.actionHelp_local = QtGui.QAction(GSTtrans)
        self.actionHelp_local.setObjectName(_fromUtf8("actionHelp_local"))
        self.actionExit = QtGui.QAction(GSTtrans)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDegrees_derived = QtGui.QAction(GSTtrans)
        self.actionDegrees_derived.setCheckable(True)
        self.actionDegrees_derived.setObjectName(_fromUtf8("actionDegrees_derived"))
        self.actionRadians_derived = QtGui.QAction(GSTtrans)
        self.actionRadians_derived.setCheckable(True)
        self.actionRadians_derived.setObjectName(_fromUtf8("actionRadians_derived"))
        self.actionSx_derived = QtGui.QAction(GSTtrans)
        self.actionSx_derived.setCheckable(True)
        self.actionSx_derived.setObjectName(_fromUtf8("actionSx_derived"))
        self.actionNt_derived = QtGui.QAction(GSTtrans)
        self.actionNt_derived.setCheckable(True)
        self.actionNt_derived.setObjectName(_fromUtf8("actionNt_derived"))
        self.actionFile2file_settings = QtGui.QAction(GSTtrans)
        self.actionFile2file_settings.setObjectName(_fromUtf8("actionFile2file_settings"))
        self.menuHelp.addAction(self.actionHelp_local)
        self.menuHelp.addAction(self.actionAbout_KMSTrans)
        self.menuFile.addAction(self.actionNew_KMSTrans)
        self.menuFile.addAction(self.actionExit)
        self.menuRegion.addAction(self.actionDK)
        self.menuRegion.addAction(self.actionFO)
        self.menuRegion.addAction(self.actionGR)
        self.menuRegion.addAction(self.actionWorld)
        self.menuAngular_units.addAction(self.actionDegrees)
        self.menuAngular_units.addAction(self.actionRadians)
        self.menuAngular_units.addAction(self.actionSx)
        self.menuAngular_units.addAction(self.actionNt)
        self.menuAngular_units_derived_output.addAction(self.actionDegrees_derived)
        self.menuAngular_units_derived_output.addAction(self.actionRadians_derived)
        self.menuAngular_units_derived_output.addAction(self.actionSx_derived)
        self.menuAngular_units_derived_output.addAction(self.actionNt_derived)
        self.menuSettings.addAction(self.menuRegion.menuAction())
        self.menuSettings.addAction(self.menuAngular_units.menuAction())
        self.menuSettings.addAction(self.menuAngular_units_derived_output.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionGeoid_directory)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionFile2file_settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(GSTtrans)
        self.tab_gsttrans.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionStation_names_in_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionStation_names_in_output.setChecked)
        QtCore.QObject.connect(self.actionStation_names_in_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionStation_names_in_output.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_f2f_ogr_driver.setEnabled)
        QtCore.QObject.connect(self.chb_f2f_label_in_file, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_f2f_input_system.setDisabled)
        QtCore.QObject.connect(self.chb_show_scale, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txt_scale.setEnabled)
        QtCore.QObject.connect(self.rdobt_bshlm_mode1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_bshlm_y2.setEnabled)
        QtCore.QObject.connect(self.rdobt_bshlm_mode1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_bshlm_x2.setEnabled)
        QtCore.QObject.connect(self.rdobt_bshlm_mode1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_bshlm_distance.setDisabled)
        QtCore.QObject.connect(self.rdobt_bshlm_mode1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_bshlm_azimuth1.setDisabled)
        QtCore.QObject.connect(self.chb_show_scale, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txt_meridian_convergence.setEnabled)
        QtCore.QObject.connect(self.chb_f2f_use_log, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_f2f_log_name.setEnabled)
        QtCore.QObject.connect(self.bt_f2f_clear_log, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txt_f2f_log.clear)
        QtCore.QObject.connect(self.chb_f2f_use_log, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chb_f2f_verbose.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.bt_f2f_input_layers.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chb_f2f_all_layers.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_f2f_layers_in.setEnabled)
        QtCore.QObject.connect(self.chb_f2f_all_layers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_f2f_layers_in.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(GSTtrans)

    def retranslateUi(self, GSTtrans):
        GSTtrans.setWindowTitle(QtGui.QApplication.translate("GSTtrans", "GSTtrans", None, QtGui.QApplication.UnicodeUTF8))
        GSTtrans.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "<html><head/><body><p>Main window</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_current_geoid_directory.setText(QtGui.QApplication.translate("GSTtrans", "Current geoid directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_geoid_dir_value.setText(QtGui.QApplication.translate("GSTtrans", "Geoid dir", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_region.setText(QtGui.QApplication.translate("GSTtrans", "Region:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_region_value.setText(QtGui.QApplication.translate("GSTtrans", "Region", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_input_info.setText(QtGui.QApplication.translate("GSTtrans", "Input system info:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_output_info.setText(QtGui.QApplication.translate("GSTtrans", "Output system info:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_input_system.setText(QtGui.QApplication.translate("GSTtrans", "Input system:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_x_in.setText(QtGui.QApplication.translate("GSTtrans", "Easting:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_y_in.setText(QtGui.QApplication.translate("GSTtrans", "Northing:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_z_in.setText(QtGui.QApplication.translate("GSTtrans", "H:", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_change_h_in.setText(QtGui.QApplication.translate("GSTtrans", "Change H", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_change_h_out.setText(QtGui.QApplication.translate("GSTtrans", "Change H", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_x_out.setText(QtGui.QApplication.translate("GSTtrans", "Easting:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_z_out.setText(QtGui.QApplication.translate("GSTtrans", "H:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_y_out.setText(QtGui.QApplication.translate("GSTtrans", "Northing:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_output_system.setText(QtGui.QApplication.translate("GSTtrans", "Output system:", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_interactive_swap.setText(QtGui.QApplication.translate("GSTtrans", "Swap input/output", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_zoom_in.setText(QtGui.QApplication.translate("GSTtrans", "zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_zoom_out.setText(QtGui.QApplication.translate("GSTtrans", "zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_zoom_to_point.setText(QtGui.QApplication.translate("GSTtrans", "Zoom to point", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_geoid_height.setText(QtGui.QApplication.translate("GSTtrans", "Geoid height:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_geoid_name.setText(QtGui.QApplication.translate("GSTtrans", "Geoid name:", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_show_scale.setText(QtGui.QApplication.translate("GSTtrans", "Show output system scale and convergence.", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_scale.setText(QtGui.QApplication.translate("GSTtrans", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_meridian_convergence.setText(QtGui.QApplication.translate("GSTtrans", "Meridian convergence:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_gsttrans.setTabText(self.tab_gsttrans.indexOf(self.tab_interactive), QtGui.QApplication.translate("GSTtrans", "Interactive", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_ogr.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "<html><head/><body><p>Perform transformations between various datasources here.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "Select input driver here...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("GSTtrans", "Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.rdobt_f2f_ogr.setText(QtGui.QApplication.translate("GSTtrans", "OGR", None, QtGui.QApplication.UnicodeUTF8))
        self.rdobt_f2f_simple_text.setText(QtGui.QApplication.translate("GSTtrans", "TEXT", None, QtGui.QApplication.UnicodeUTF8))
        self.rdobt_f2f_dsfl.setText(QtGui.QApplication.translate("GSTtrans", "DSFL", None, QtGui.QApplication.UnicodeUTF8))
        self.rdobt_f2f_kmsformat.setText(QtGui.QApplication.translate("GSTtrans", "KMSformat", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_settings.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "Open settings specific for the TEXT format.", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_settings.setText(QtGui.QApplication.translate("GSTtrans", "Open TEXT settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("GSTtrans", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_f2f_input_file.setText(QtGui.QApplication.translate("GSTtrans", "Input path or connection string: ", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_f2f_input_file.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "<html><head/><body><p>A simple file name or, if using OGR, a connection string to e.g. a database.</p><p>Use * wildcards for globbing over several  input files in a directory.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_browse_input.setText(QtGui.QApplication.translate("GSTtrans", "Browse files", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_browse_input_dir.setText(QtGui.QApplication.translate("GSTtrans", "Browse dirs", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_all_layers.setText(QtGui.QApplication.translate("GSTtrans", "Transform all layers, or specify layers here:", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_f2f_layers_in.setToolTip(QtGui.QApplication.translate("GSTtrans", "Semicolon separated list of layers", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_f2f_layers_in.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "<html><head/><body><p>Specify input layers here, seperated by semicolons. Only valid for OGR input/output and formats that support layers, e.g. a directory of shape files or a FileGDB database.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_input_layers.setText(QtGui.QApplication.translate("GSTtrans", "Select input layers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("GSTtrans", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_f2f_ogrdriver.setText(QtGui.QApplication.translate("GSTtrans", "Output format will equal input format, except for OGR input driver, where output format can be chosen:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_f2f_output_file.setText(QtGui.QApplication.translate("GSTtrans", "Output path or connection string:", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_browse_output.setText(QtGui.QApplication.translate("GSTtrans", "Browse files", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_browse_output_dir.setText(QtGui.QApplication.translate("GSTtrans", "Browse dirs", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_use_log.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "Use a log file to log errors and other output from TrLib.", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_use_log.setText(QtGui.QApplication.translate("GSTtrans", "Use log file", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_verbose.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "Turn on extra verbosity in logging.", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_verbose.setText(QtGui.QApplication.translate("GSTtrans", "Verbose output", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_browse_log.setText(QtGui.QApplication.translate("GSTtrans", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GSTtrans", "Transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_f2f_input_info.setText(QtGui.QApplication.translate("GSTtrans", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_f2f_output_info.setText(QtGui.QApplication.translate("GSTtrans", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_label_in_file.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "Use this option if projection metadata is extractable from the input datasource.", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_label_in_file.setText(QtGui.QApplication.translate("GSTtrans", "Label in file", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_set_projection.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "<html><head/><body><p>If checked, will attempt to write output projection metadata in destionation datasource.</p><p>This might fail for some OGR-drivers like e.g. \'FileGDB\', in which case the metadata can be attached via some appropriate tool afterwards, like e.g. ogr2ogr. </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_f2f_set_projection.setText(QtGui.QApplication.translate("GSTtrans", "Set output projection metadata in destination", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GSTtrans", "Input system:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_f2f_input_system.setToolTip(QtGui.QApplication.translate("GSTtrans", "Specify input system", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_change_h_in.setText(QtGui.QApplication.translate("GSTtrans", "Change H", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GSTtrans", "Output system:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_f2f_output_system.setToolTip(QtGui.QApplication.translate("GSTtrans", "Specify putput system", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_change_h_out.setText(QtGui.QApplication.translate("GSTtrans", "Change H", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_f2f_log.setWhatsThis(QtGui.QApplication.translate("GSTtrans", "Output log from batch transformation.", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_execute.setText(QtGui.QApplication.translate("GSTtrans", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_view_output.setText(QtGui.QApplication.translate("GSTtrans", "View output", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_view_log.setText(QtGui.QApplication.translate("GSTtrans", "View log file", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_f2f_clear_log.setText(QtGui.QApplication.translate("GSTtrans", "Clear log window", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_gsttrans.setTabText(self.tab_gsttrans.indexOf(self.tab_ogr), QtGui.QApplication.translate("GSTtrans", "Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_bshlm.setTitle(QtGui.QApplication.translate("GSTtrans", "Bessel Helmert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("GSTtrans", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_description.setText(QtGui.QApplication.translate("GSTtrans", "system info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GSTtrans", "Coordinate system:", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_bshlm_custom_ellipsoid.setText(QtGui.QApplication.translate("GSTtrans", "Custom Ellipsoid", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_ellipsoid.setText(QtGui.QApplication.translate("GSTtrans", "Ellipsoid:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GSTtrans", "Inverse flattening:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GSTtrans", "Major axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_x.setText(QtGui.QApplication.translate("GSTtrans", "Easting:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_y.setText(QtGui.QApplication.translate("GSTtrans", "Northing:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_station1.setText(QtGui.QApplication.translate("GSTtrans", "Station 1 ", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_station2.setText(QtGui.QApplication.translate("GSTtrans", "Station 2", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_lon.setText(QtGui.QApplication.translate("GSTtrans", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_bshlm_lat.setText(QtGui.QApplication.translate("GSTtrans", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GSTtrans", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GSTtrans", "Forward Azimuth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GSTtrans", "Backwards Azimuth:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("GSTtrans", "Calculation mode", None, QtGui.QApplication.UnicodeUTF8))
        self.rdobt_bshlm_mode1.setText(QtGui.QApplication.translate("GSTtrans", "Find distance and azimuth from positions of station1 and  station2.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdobt_bshlm_mode2.setText(QtGui.QApplication.translate("GSTtrans", "Find position of station2 based on distance and azimuth from station1. ", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_gsttrans.setTabText(self.tab_gsttrans.indexOf(self.tab_utilities), QtGui.QApplication.translate("GSTtrans", "Bessel Helmert", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_gsttrans.setTabToolTip(self.tab_gsttrans.indexOf(self.tab_utilities), QtGui.QApplication.translate("GSTtrans", "Varoious geodetic utilities", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_python_run.setText(QtGui.QApplication.translate("GSTtrans", "compile", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_python_load.setText(QtGui.QApplication.translate("GSTtrans", "load script", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_python_process_enter.setText(QtGui.QApplication.translate("GSTtrans", "Run command on enter (REPL mode)", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_python_clear.setText(QtGui.QApplication.translate("GSTtrans", "Clear input code on succes", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_gsttrans.setTabText(self.tab_gsttrans.indexOf(self.tab_python), QtGui.QApplication.translate("GSTtrans", "Python console", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_gsttrans.setTabToolTip(self.tab_gsttrans.indexOf(self.tab_python), QtGui.QApplication.translate("GSTtrans", "Tab for interactive python session.", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("GSTtrans", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("GSTtrans", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("GSTtrans", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRegion.setTitle(QtGui.QApplication.translate("GSTtrans", "Region", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAngular_units.setTitle(QtGui.QApplication.translate("GSTtrans", "Angular units (coordinates)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAngular_units_derived_output.setTitle(QtGui.QApplication.translate("GSTtrans", "Angular units (derived output)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_KMSTrans.setText(QtGui.QApplication.translate("GSTtrans", "New KMSTrans", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_KMSTrans.setText(QtGui.QApplication.translate("GSTtrans", "About KMSTrans", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("GSTtrans", "Online help pages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setIconText(QtGui.QApplication.translate("GSTtrans", "www help page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDK.setText(QtGui.QApplication.translate("GSTtrans", "Denmark", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFO.setText(QtGui.QApplication.translate("GSTtrans", "Faroe Islands", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGR.setText(QtGui.QApplication.translate("GSTtrans", "Greenland", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWorld.setText(QtGui.QApplication.translate("GSTtrans", "World", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDegrees.setText(QtGui.QApplication.translate("GSTtrans", "degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRadians.setText(QtGui.QApplication.translate("GSTtrans", "radians", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSx.setText(QtGui.QApplication.translate("GSTtrans", "sx: ddd mm ss.sss", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNt.setText(QtGui.QApplication.translate("GSTtrans", "nt: ddd mm.mmmm", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeoid_directory.setText(QtGui.QApplication.translate("GSTtrans", "Geoid directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStation_names_in_input.setText(QtGui.QApplication.translate("GSTtrans", "Station names in input", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStation_names_in_output.setText(QtGui.QApplication.translate("GSTtrans", "Station names in output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerbose_output.setText(QtGui.QApplication.translate("GSTtrans", "Verbose output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp_local.setText(QtGui.QApplication.translate("GSTtrans", "Local help pages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("GSTtrans", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDegrees_derived.setText(QtGui.QApplication.translate("GSTtrans", "degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRadians_derived.setText(QtGui.QApplication.translate("GSTtrans", "radians", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSx_derived.setText(QtGui.QApplication.translate("GSTtrans", "sx: ddd mm ss.sss", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNt_derived.setText(QtGui.QApplication.translate("GSTtrans", "nt: ddd mm.mmmm", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile2file_settings.setText(QtGui.QApplication.translate("GSTtrans", "File2file settings", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    GSTtrans = QtGui.QMainWindow()
    ui = Ui_GSTtrans()
    ui.setupUi(GSTtrans)
    GSTtrans.show()
    sys.exit(app.exec_())

