# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Trui.ui'
#
# Created: Mon May 27 14:42:19 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Trui(object):
    def setupUi(self, Trui):
        Trui.setObjectName(_fromUtf8("Trui"))
        Trui.resize(1013, 721)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Trui.sizePolicy().hasHeightForWidth())
        Trui.setSizePolicy(sizePolicy)
        Trui.setMinimumSize(QtCore.QSize(650, 550))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Trui.setPalette(palette)
        Trui.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Trui.setWindowIcon(icon)
        Trui.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(Trui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.lbl_current_geoid_directory = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_current_geoid_directory.setFont(font)
        self.lbl_current_geoid_directory.setObjectName(_fromUtf8("lbl_current_geoid_directory"))
        self.gridLayout_20.addWidget(self.lbl_current_geoid_directory, 0, 6, 1, 1)
        self.lbl_geoid_dir_value = QtGui.QLabel(self.centralwidget)
        self.lbl_geoid_dir_value.setObjectName(_fromUtf8("lbl_geoid_dir_value"))
        self.gridLayout_20.addWidget(self.lbl_geoid_dir_value, 0, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem, 0, 10, 1, 1)
        self.lbl_region = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_region.setFont(font)
        self.lbl_region.setObjectName(_fromUtf8("lbl_region"))
        self.gridLayout_20.addWidget(self.lbl_region, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem1, 0, 5, 1, 1)
        self.lbl_region_value = QtGui.QLabel(self.centralwidget)
        self.lbl_region_value.setObjectName(_fromUtf8("lbl_region_value"))
        self.gridLayout_20.addWidget(self.lbl_region_value, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem2, 0, 2, 1, 1)
        self.lbl_geo_coords = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_geo_coords.setFont(font)
        self.lbl_geo_coords.setObjectName(_fromUtf8("lbl_geo_coords"))
        self.gridLayout_20.addWidget(self.lbl_geo_coords, 0, 3, 1, 1)
        self.lbl_geo_coords_value = QtGui.QLabel(self.centralwidget)
        self.lbl_geo_coords_value.setObjectName(_fromUtf8("lbl_geo_coords_value"))
        self.gridLayout_20.addWidget(self.lbl_geo_coords_value, 0, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_20, 1, 0, 1, 1)
        self.main_tab_host = QtGui.QTabWidget(self.centralwidget)
        self.main_tab_host.setObjectName(_fromUtf8("main_tab_host"))
        self.tab_interactive = QtGui.QWidget()
        self.tab_interactive.setObjectName(_fromUtf8("tab_interactive"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_interactive)
        self.verticalLayout_3.setContentsMargins(-1, 13, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl_input_info = QtGui.QLabel(self.tab_interactive)
        self.lbl_input_info.setObjectName(_fromUtf8("lbl_input_info"))
        self.verticalLayout_2.addWidget(self.lbl_input_info)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.lbl_output_info = QtGui.QLabel(self.tab_interactive)
        self.lbl_output_info.setObjectName(_fromUtf8("lbl_output_info"))
        self.verticalLayout_2.addWidget(self.lbl_output_info)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_input_system = QtGui.QLabel(self.tab_interactive)
        self.lbl_input_system.setObjectName(_fromUtf8("lbl_input_system"))
        self.gridLayout_2.addWidget(self.lbl_input_system, 0, 0, 1, 1)
        self.lbl_x_in = QtGui.QLabel(self.tab_interactive)
        self.lbl_x_in.setObjectName(_fromUtf8("lbl_x_in"))
        self.gridLayout_2.addWidget(self.lbl_x_in, 0, 2, 1, 1)
        self.lbl_y_in = QtGui.QLabel(self.tab_interactive)
        self.lbl_y_in.setObjectName(_fromUtf8("lbl_y_in"))
        self.gridLayout_2.addWidget(self.lbl_y_in, 0, 3, 1, 1)
        self.lbl_z_in = QtGui.QLabel(self.tab_interactive)
        self.lbl_z_in.setObjectName(_fromUtf8("lbl_z_in"))
        self.gridLayout_2.addWidget(self.lbl_z_in, 0, 4, 1, 1)
        self.cb_input_system = QtGui.QComboBox(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_input_system.sizePolicy().hasHeightForWidth())
        self.cb_input_system.setSizePolicy(sizePolicy)
        self.cb_input_system.setEditable(True)
        self.cb_input_system.setObjectName(_fromUtf8("cb_input_system"))
        self.gridLayout_2.addWidget(self.cb_input_system, 1, 0, 1, 1)
        self.bt_change_h_in = QtGui.QPushButton(self.tab_interactive)
        self.bt_change_h_in.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bt_change_h_in.setObjectName(_fromUtf8("bt_change_h_in"))
        self.gridLayout_2.addWidget(self.bt_change_h_in, 1, 1, 1, 1)
        self.txt_x_in = QtGui.QLineEdit(self.tab_interactive)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_x_in.setPalette(palette)
        self.txt_x_in.setText(_fromUtf8(""))
        self.txt_x_in.setObjectName(_fromUtf8("txt_x_in"))
        self.gridLayout_2.addWidget(self.txt_x_in, 1, 2, 1, 1)
        self.txt_y_in = QtGui.QLineEdit(self.tab_interactive)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_y_in.setPalette(palette)
        self.txt_y_in.setObjectName(_fromUtf8("txt_y_in"))
        self.gridLayout_2.addWidget(self.txt_y_in, 1, 3, 1, 1)
        self.txt_z_in = QtGui.QLineEdit(self.tab_interactive)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_z_in.setPalette(palette)
        self.txt_z_in.setObjectName(_fromUtf8("txt_z_in"))
        self.gridLayout_2.addWidget(self.txt_z_in, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem6 = QtGui.QSpacerItem(761, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.txt_x_out = QtGui.QLineEdit(self.tab_interactive)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_x_out.setPalette(palette)
        self.txt_x_out.setReadOnly(True)
        self.txt_x_out.setObjectName(_fromUtf8("txt_x_out"))
        self.gridLayout_3.addWidget(self.txt_x_out, 1, 2, 1, 1)
        self.bt_change_h_out = QtGui.QPushButton(self.tab_interactive)
        self.bt_change_h_out.setObjectName(_fromUtf8("bt_change_h_out"))
        self.gridLayout_3.addWidget(self.bt_change_h_out, 1, 1, 1, 1)
        self.txt_y_out = QtGui.QLineEdit(self.tab_interactive)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_y_out.setPalette(palette)
        self.txt_y_out.setReadOnly(True)
        self.txt_y_out.setObjectName(_fromUtf8("txt_y_out"))
        self.gridLayout_3.addWidget(self.txt_y_out, 1, 3, 1, 1)
        self.cb_output_system = QtGui.QComboBox(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_output_system.sizePolicy().hasHeightForWidth())
        self.cb_output_system.setSizePolicy(sizePolicy)
        self.cb_output_system.setEditable(True)
        self.cb_output_system.setObjectName(_fromUtf8("cb_output_system"))
        self.gridLayout_3.addWidget(self.cb_output_system, 1, 0, 1, 1)
        self.txt_z_out = QtGui.QLineEdit(self.tab_interactive)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_z_out.setPalette(palette)
        self.txt_z_out.setReadOnly(True)
        self.txt_z_out.setObjectName(_fromUtf8("txt_z_out"))
        self.gridLayout_3.addWidget(self.txt_z_out, 1, 4, 1, 1)
        self.lbl_x_out = QtGui.QLabel(self.tab_interactive)
        self.lbl_x_out.setObjectName(_fromUtf8("lbl_x_out"))
        self.gridLayout_3.addWidget(self.lbl_x_out, 0, 2, 1, 1)
        self.lbl_z_out = QtGui.QLabel(self.tab_interactive)
        self.lbl_z_out.setObjectName(_fromUtf8("lbl_z_out"))
        self.gridLayout_3.addWidget(self.lbl_z_out, 0, 4, 1, 1)
        self.lbl_y_out = QtGui.QLabel(self.tab_interactive)
        self.lbl_y_out.setObjectName(_fromUtf8("lbl_y_out"))
        self.gridLayout_3.addWidget(self.lbl_y_out, 0, 3, 1, 1)
        self.lbl_output_system = QtGui.QLabel(self.tab_interactive)
        self.lbl_output_system.setObjectName(_fromUtf8("lbl_output_system"))
        self.gridLayout_3.addWidget(self.lbl_output_system, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bt_interactive_swap = QtGui.QPushButton(self.tab_interactive)
        self.bt_interactive_swap.setObjectName(_fromUtf8("bt_interactive_swap"))
        self.horizontalLayout_3.addWidget(self.bt_interactive_swap)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.bt_interactive_transform = QtGui.QPushButton(self.tab_interactive)
        self.bt_interactive_transform.setObjectName(_fromUtf8("bt_interactive_transform"))
        self.horizontalLayout_3.addWidget(self.bt_interactive_transform)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gv_map = QtGui.QGraphicsView(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_map.sizePolicy().hasHeightForWidth())
        self.gv_map.setSizePolicy(sizePolicy)
        self.gv_map.setBaseSize(QtCore.QSize(360, 180))
        self.gv_map.setObjectName(_fromUtf8("gv_map"))
        self.horizontalLayout_2.addWidget(self.gv_map)
        self.gridLayout_18.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.bt_zoom_in = QtGui.QPushButton(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_zoom_in.sizePolicy().hasHeightForWidth())
        self.bt_zoom_in.setSizePolicy(sizePolicy)
        self.bt_zoom_in.setObjectName(_fromUtf8("bt_zoom_in"))
        self.gridLayout_19.addWidget(self.bt_zoom_in, 1, 0, 1, 1)
        self.bt_zoom_out = QtGui.QPushButton(self.tab_interactive)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_zoom_out.sizePolicy().hasHeightForWidth())
        self.bt_zoom_out.setSizePolicy(sizePolicy)
        self.bt_zoom_out.setObjectName(_fromUtf8("bt_zoom_out"))
        self.gridLayout_19.addWidget(self.bt_zoom_out, 2, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem9, 1, 1, 1, 1)
        self.chb_zoom_to_point = QtGui.QCheckBox(self.tab_interactive)
        self.chb_zoom_to_point.setChecked(True)
        self.chb_zoom_to_point.setObjectName(_fromUtf8("chb_zoom_to_point"))
        self.gridLayout_19.addWidget(self.chb_zoom_to_point, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_19, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_18)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lbl_geoid_height = QtGui.QLabel(self.tab_interactive)
        self.lbl_geoid_height.setObjectName(_fromUtf8("lbl_geoid_height"))
        self.gridLayout_6.addWidget(self.lbl_geoid_height, 0, 0, 1, 1)
        self.lbl_geoid_name = QtGui.QLabel(self.tab_interactive)
        self.lbl_geoid_name.setObjectName(_fromUtf8("lbl_geoid_name"))
        self.gridLayout_6.addWidget(self.lbl_geoid_name, 0, 1, 1, 1)
        self.txt_geoid_height = QtGui.QLineEdit(self.tab_interactive)
        self.txt_geoid_height.setAcceptDrops(False)
        self.txt_geoid_height.setReadOnly(True)
        self.txt_geoid_height.setObjectName(_fromUtf8("txt_geoid_height"))
        self.gridLayout_6.addWidget(self.txt_geoid_height, 1, 0, 1, 1)
        self.txt_geoid_name = QtGui.QLineEdit(self.tab_interactive)
        self.txt_geoid_name.setEnabled(True)
        self.txt_geoid_name.setAcceptDrops(False)
        self.txt_geoid_name.setReadOnly(True)
        self.txt_geoid_name.setObjectName(_fromUtf8("txt_geoid_name"))
        self.gridLayout_6.addWidget(self.txt_geoid_name, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.chb_show_scale = QtGui.QCheckBox(self.tab_interactive)
        self.chb_show_scale.setObjectName(_fromUtf8("chb_show_scale"))
        self.verticalLayout_4.addWidget(self.chb_show_scale)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.lbl_scale = QtGui.QLabel(self.tab_interactive)
        self.lbl_scale.setObjectName(_fromUtf8("lbl_scale"))
        self.gridLayout_21.addWidget(self.lbl_scale, 0, 0, 1, 1)
        self.lbl_meridian_convergence = QtGui.QLabel(self.tab_interactive)
        self.lbl_meridian_convergence.setObjectName(_fromUtf8("lbl_meridian_convergence"))
        self.gridLayout_21.addWidget(self.lbl_meridian_convergence, 0, 1, 1, 1)
        self.txt_scale = QtGui.QLineEdit(self.tab_interactive)
        self.txt_scale.setEnabled(False)
        self.txt_scale.setAcceptDrops(False)
        self.txt_scale.setToolTip(_fromUtf8(""))
        self.txt_scale.setReadOnly(True)
        self.txt_scale.setObjectName(_fromUtf8("txt_scale"))
        self.gridLayout_21.addWidget(self.txt_scale, 1, 0, 1, 1)
        self.txt_meridian_convergence = QtGui.QLineEdit(self.tab_interactive)
        self.txt_meridian_convergence.setEnabled(False)
        self.txt_meridian_convergence.setAcceptDrops(False)
        self.txt_meridian_convergence.setReadOnly(True)
        self.txt_meridian_convergence.setObjectName(_fromUtf8("txt_meridian_convergence"))
        self.gridLayout_21.addWidget(self.txt_meridian_convergence, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_21)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.txt_log = QtGui.QTextEdit(self.tab_interactive)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.horizontalLayout.addWidget(self.txt_log)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.main_tab_host.addTab(self.tab_interactive, _fromUtf8(""))
        self.tab_ogr = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ogr.sizePolicy().hasHeightForWidth())
        self.tab_ogr.setSizePolicy(sizePolicy)
        self.tab_ogr.setObjectName(_fromUtf8("tab_ogr"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_ogr)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setBaseSize(QtCore.QSize(0, 24))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.rdobt_f2f_ogr = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_ogr.setChecked(True)
        self.rdobt_f2f_ogr.setObjectName(_fromUtf8("rdobt_f2f_ogr"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_ogr)
        self.rdobt_f2f_simple_text = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_simple_text.setObjectName(_fromUtf8("rdobt_f2f_simple_text"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_simple_text)
        self.rdobt_f2f_dsfl = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_dsfl.setObjectName(_fromUtf8("rdobt_f2f_dsfl"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_dsfl)
        self.rdobt_f2f_kmsformat = QtGui.QRadioButton(self.groupBox_5)
        self.rdobt_f2f_kmsformat.setObjectName(_fromUtf8("rdobt_f2f_kmsformat"))
        self.horizontalLayout_9.addWidget(self.rdobt_f2f_kmsformat)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_f2f_input_file = QtGui.QLabel(self.groupBox_3)
        self.lbl_f2f_input_file.setObjectName(_fromUtf8("lbl_f2f_input_file"))
        self.horizontalLayout_5.addWidget(self.lbl_f2f_input_file)
        self.txt_f2f_input_file = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_f2f_input_file.sizePolicy().hasHeightForWidth())
        self.txt_f2f_input_file.setSizePolicy(sizePolicy)
        self.txt_f2f_input_file.setSizeIncrement(QtCore.QSize(0, 0))
        self.txt_f2f_input_file.setObjectName(_fromUtf8("txt_f2f_input_file"))
        self.horizontalLayout_5.addWidget(self.txt_f2f_input_file)
        self.bt_f2f_browse_input = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_browse_input.sizePolicy().hasHeightForWidth())
        self.bt_f2f_browse_input.setSizePolicy(sizePolicy)
        self.bt_f2f_browse_input.setObjectName(_fromUtf8("bt_f2f_browse_input"))
        self.horizontalLayout_5.addWidget(self.bt_f2f_browse_input)
        self.bt_f2f_browse_input_dir = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_browse_input_dir.sizePolicy().hasHeightForWidth())
        self.bt_f2f_browse_input_dir.setSizePolicy(sizePolicy)
        self.bt_f2f_browse_input_dir.setObjectName(_fromUtf8("bt_f2f_browse_input_dir"))
        self.horizontalLayout_5.addWidget(self.bt_f2f_browse_input_dir)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.chb_f2f_all_layers = QtGui.QCheckBox(self.groupBox_3)
        self.chb_f2f_all_layers.setChecked(True)
        self.chb_f2f_all_layers.setObjectName(_fromUtf8("chb_f2f_all_layers"))
        self.horizontalLayout_12.addWidget(self.chb_f2f_all_layers)
        self.txt_f2f_layers_in = QtGui.QLineEdit(self.groupBox_3)
        self.txt_f2f_layers_in.setEnabled(False)
        self.txt_f2f_layers_in.setObjectName(_fromUtf8("txt_f2f_layers_in"))
        self.horizontalLayout_12.addWidget(self.txt_f2f_layers_in)
        self.bt_f2f_input_layers = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_input_layers.sizePolicy().hasHeightForWidth())
        self.bt_f2f_input_layers.setSizePolicy(sizePolicy)
        self.bt_f2f_input_layers.setObjectName(_fromUtf8("bt_f2f_input_layers"))
        self.horizontalLayout_12.addWidget(self.bt_f2f_input_layers)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_ogr)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_f2f_ogrdriver = QtGui.QLabel(self.groupBox_4)
        self.lbl_f2f_ogrdriver.setObjectName(_fromUtf8("lbl_f2f_ogrdriver"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_f2f_ogrdriver)
        self.cb_f2f_ogr_driver = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_f2f_ogr_driver.sizePolicy().hasHeightForWidth())
        self.cb_f2f_ogr_driver.setSizePolicy(sizePolicy)
        self.cb_f2f_ogr_driver.setObjectName(_fromUtf8("cb_f2f_ogr_driver"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_f2f_ogr_driver)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.bt_f2f_creation_options = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_creation_options.sizePolicy().hasHeightForWidth())
        self.bt_f2f_creation_options.setSizePolicy(sizePolicy)
        self.bt_f2f_creation_options.setObjectName(_fromUtf8("bt_f2f_creation_options"))
        self.horizontalLayout_4.addWidget(self.bt_f2f_creation_options)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lbl_f2f_output_file = QtGui.QLabel(self.groupBox_4)
        self.lbl_f2f_output_file.setObjectName(_fromUtf8("lbl_f2f_output_file"))
        self.horizontalLayout_6.addWidget(self.lbl_f2f_output_file)
        self.txt_f2f_output_file = QtGui.QLineEdit(self.groupBox_4)
        self.txt_f2f_output_file.setObjectName(_fromUtf8("txt_f2f_output_file"))
        self.horizontalLayout_6.addWidget(self.txt_f2f_output_file)
        self.bt_f2f_browse_output = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_browse_output.sizePolicy().hasHeightForWidth())
        self.bt_f2f_browse_output.setSizePolicy(sizePolicy)
        self.bt_f2f_browse_output.setObjectName(_fromUtf8("bt_f2f_browse_output"))
        self.horizontalLayout_6.addWidget(self.bt_f2f_browse_output)
        self.bt_f2f_browse_output_dir = QtGui.QPushButton(self.groupBox_4)
        self.bt_f2f_browse_output_dir.setObjectName(_fromUtf8("bt_f2f_browse_output_dir"))
        self.horizontalLayout_6.addWidget(self.bt_f2f_browse_output_dir)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chb_f2f_use_log = QtGui.QCheckBox(self.tab_ogr)
        self.chb_f2f_use_log.setChecked(False)
        self.chb_f2f_use_log.setTristate(False)
        self.chb_f2f_use_log.setObjectName(_fromUtf8("chb_f2f_use_log"))
        self.horizontalLayout_11.addWidget(self.chb_f2f_use_log)
        self.chb_f2f_verbose = QtGui.QCheckBox(self.tab_ogr)
        self.chb_f2f_verbose.setChecked(False)
        self.chb_f2f_verbose.setObjectName(_fromUtf8("chb_f2f_verbose"))
        self.horizontalLayout_11.addWidget(self.chb_f2f_verbose)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.txt_f2f_log_name = QtGui.QLineEdit(self.tab_ogr)
        self.txt_f2f_log_name.setEnabled(False)
        self.txt_f2f_log_name.setObjectName(_fromUtf8("txt_f2f_log_name"))
        self.horizontalLayout_11.addWidget(self.txt_f2f_log_name)
        self.bt_f2f_browse_log = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_browse_log.setObjectName(_fromUtf8("bt_f2f_browse_log"))
        self.horizontalLayout_11.addWidget(self.bt_f2f_browse_log)
        spacerItem17 = QtGui.QSpacerItem(170, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.lbl_f2f_input_info = QtGui.QLabel(self.groupBox_2)
        self.lbl_f2f_input_info.setObjectName(_fromUtf8("lbl_f2f_input_info"))
        self.verticalLayout_12.addWidget(self.lbl_f2f_input_info)
        self.lbl_f2f_output_info = QtGui.QLabel(self.groupBox_2)
        self.lbl_f2f_output_info.setObjectName(_fromUtf8("lbl_f2f_output_info"))
        self.verticalLayout_12.addWidget(self.lbl_f2f_output_info)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chb_f2f_label_in_file = QtGui.QCheckBox(self.groupBox_2)
        self.chb_f2f_label_in_file.setObjectName(_fromUtf8("chb_f2f_label_in_file"))
        self.horizontalLayout_10.addWidget(self.chb_f2f_label_in_file)
        self.chb_f2f_set_projection = QtGui.QCheckBox(self.groupBox_2)
        self.chb_f2f_set_projection.setChecked(True)
        self.chb_f2f_set_projection.setObjectName(_fromUtf8("chb_f2f_set_projection"))
        self.horizontalLayout_10.addWidget(self.chb_f2f_set_projection)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        spacerItem19 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem19)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.cb_f2f_input_system = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_f2f_input_system.sizePolicy().hasHeightForWidth())
        self.cb_f2f_input_system.setSizePolicy(sizePolicy)
        self.cb_f2f_input_system.setMinimumSize(QtCore.QSize(0, 20))
        self.cb_f2f_input_system.setEditable(True)
        self.cb_f2f_input_system.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_f2f_input_system.setObjectName(_fromUtf8("cb_f2f_input_system"))
        self.horizontalLayout_8.addWidget(self.cb_f2f_input_system)
        self.bt_f2f_change_h_in = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_change_h_in.sizePolicy().hasHeightForWidth())
        self.bt_f2f_change_h_in.setSizePolicy(sizePolicy)
        self.bt_f2f_change_h_in.setMinimumSize(QtCore.QSize(0, 23))
        self.bt_f2f_change_h_in.setObjectName(_fromUtf8("bt_f2f_change_h_in"))
        self.horizontalLayout_8.addWidget(self.bt_f2f_change_h_in)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.cb_f2f_output_system = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_f2f_output_system.sizePolicy().hasHeightForWidth())
        self.cb_f2f_output_system.setSizePolicy(sizePolicy)
        self.cb_f2f_output_system.setMinimumSize(QtCore.QSize(0, 20))
        self.cb_f2f_output_system.setEditable(True)
        self.cb_f2f_output_system.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_f2f_output_system.setObjectName(_fromUtf8("cb_f2f_output_system"))
        self.horizontalLayout_8.addWidget(self.cb_f2f_output_system)
        self.bt_f2f_change_h_out = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_change_h_out.sizePolicy().hasHeightForWidth())
        self.bt_f2f_change_h_out.setSizePolicy(sizePolicy)
        self.bt_f2f_change_h_out.setMinimumSize(QtCore.QSize(0, 23))
        self.bt_f2f_change_h_out.setObjectName(_fromUtf8("bt_f2f_change_h_out"))
        self.horizontalLayout_8.addWidget(self.bt_f2f_change_h_out)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem20 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.txt_f2f_log = QtGui.QTextEdit(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_f2f_log.sizePolicy().hasHeightForWidth())
        self.txt_f2f_log.setSizePolicy(sizePolicy)
        self.txt_f2f_log.setMaximumSize(QtCore.QSize(16777215, 132))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(9)
        self.txt_f2f_log.setFont(font)
        self.txt_f2f_log.setReadOnly(True)
        self.txt_f2f_log.setObjectName(_fromUtf8("txt_f2f_log"))
        self.verticalLayout_5.addWidget(self.txt_f2f_log)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bt_f2f_execute = QtGui.QPushButton(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_execute.sizePolicy().hasHeightForWidth())
        self.bt_f2f_execute.setSizePolicy(sizePolicy)
        self.bt_f2f_execute.setObjectName(_fromUtf8("bt_f2f_execute"))
        self.gridLayout.addWidget(self.bt_f2f_execute, 0, 0, 1, 1)
        self.bt_f2f_view_output = QtGui.QPushButton(self.tab_ogr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_f2f_view_output.sizePolicy().hasHeightForWidth())
        self.bt_f2f_view_output.setSizePolicy(sizePolicy)
        self.bt_f2f_view_output.setObjectName(_fromUtf8("bt_f2f_view_output"))
        self.gridLayout.addWidget(self.bt_f2f_view_output, 0, 1, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 0, 6, 1, 1)
        self.bt_f2f_view_log = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_view_log.setObjectName(_fromUtf8("bt_f2f_view_log"))
        self.gridLayout.addWidget(self.bt_f2f_view_log, 0, 2, 1, 1)
        self.bt_f2f_clear_log = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_clear_log.setObjectName(_fromUtf8("bt_f2f_clear_log"))
        self.gridLayout.addWidget(self.bt_f2f_clear_log, 0, 4, 1, 1)
        self.bt_f2f_kill = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_kill.setEnabled(False)
        self.bt_f2f_kill.setObjectName(_fromUtf8("bt_f2f_kill"))
        self.gridLayout.addWidget(self.bt_f2f_kill, 0, 5, 1, 1)
        self.bt_f2f_list_formats = QtGui.QPushButton(self.tab_ogr)
        self.bt_f2f_list_formats.setObjectName(_fromUtf8("bt_f2f_list_formats"))
        self.gridLayout.addWidget(self.bt_f2f_list_formats, 0, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.main_tab_host.addTab(self.tab_ogr, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.main_tab_host, 0, 0, 1, 1)
        Trui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Trui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuRegion = QtGui.QMenu(self.menuSettings)
        self.menuRegion.setObjectName(_fromUtf8("menuRegion"))
        self.menuAngular_units = QtGui.QMenu(self.menuSettings)
        self.menuAngular_units.setObjectName(_fromUtf8("menuAngular_units"))
        self.menuAngular_units_derived_output = QtGui.QMenu(self.menuSettings)
        self.menuAngular_units_derived_output.setObjectName(_fromUtf8("menuAngular_units_derived_output"))
        Trui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Trui)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Trui.setStatusBar(self.statusbar)
        self.actionNew_KMSTrans = QtGui.QAction(Trui)
        self.actionNew_KMSTrans.setObjectName(_fromUtf8("actionNew_KMSTrans"))
        self.actionAbout_KMSTrans = QtGui.QAction(Trui)
        self.actionAbout_KMSTrans.setObjectName(_fromUtf8("actionAbout_KMSTrans"))
        self.actionHelp = QtGui.QAction(Trui)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionDK = QtGui.QAction(Trui)
        self.actionDK.setObjectName(_fromUtf8("actionDK"))
        self.actionFO = QtGui.QAction(Trui)
        self.actionFO.setObjectName(_fromUtf8("actionFO"))
        self.actionGR = QtGui.QAction(Trui)
        self.actionGR.setObjectName(_fromUtf8("actionGR"))
        self.actionWorld = QtGui.QAction(Trui)
        self.actionWorld.setObjectName(_fromUtf8("actionWorld"))
        self.actionDegrees = QtGui.QAction(Trui)
        self.actionDegrees.setCheckable(True)
        self.actionDegrees.setObjectName(_fromUtf8("actionDegrees"))
        self.actionRadians = QtGui.QAction(Trui)
        self.actionRadians.setCheckable(True)
        self.actionRadians.setObjectName(_fromUtf8("actionRadians"))
        self.actionSx = QtGui.QAction(Trui)
        self.actionSx.setCheckable(True)
        self.actionSx.setObjectName(_fromUtf8("actionSx"))
        self.actionNt = QtGui.QAction(Trui)
        self.actionNt.setCheckable(True)
        self.actionNt.setAutoRepeat(True)
        self.actionNt.setObjectName(_fromUtf8("actionNt"))
        self.actionGeoid_directory = QtGui.QAction(Trui)
        self.actionGeoid_directory.setObjectName(_fromUtf8("actionGeoid_directory"))
        self.actionStation_names_in_input = QtGui.QAction(Trui)
        self.actionStation_names_in_input.setCheckable(True)
        self.actionStation_names_in_input.setObjectName(_fromUtf8("actionStation_names_in_input"))
        self.actionStation_names_in_output = QtGui.QAction(Trui)
        self.actionStation_names_in_output.setCheckable(True)
        self.actionStation_names_in_output.setEnabled(False)
        self.actionStation_names_in_output.setObjectName(_fromUtf8("actionStation_names_in_output"))
        self.actionVerbose_output = QtGui.QAction(Trui)
        self.actionVerbose_output.setCheckable(True)
        self.actionVerbose_output.setChecked(True)
        self.actionVerbose_output.setObjectName(_fromUtf8("actionVerbose_output"))
        self.actionHelp_local = QtGui.QAction(Trui)
        self.actionHelp_local.setObjectName(_fromUtf8("actionHelp_local"))
        self.actionExit = QtGui.QAction(Trui)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDegrees_derived = QtGui.QAction(Trui)
        self.actionDegrees_derived.setCheckable(True)
        self.actionDegrees_derived.setObjectName(_fromUtf8("actionDegrees_derived"))
        self.actionRadians_derived = QtGui.QAction(Trui)
        self.actionRadians_derived.setCheckable(True)
        self.actionRadians_derived.setObjectName(_fromUtf8("actionRadians_derived"))
        self.actionSx_derived = QtGui.QAction(Trui)
        self.actionSx_derived.setCheckable(True)
        self.actionSx_derived.setObjectName(_fromUtf8("actionSx_derived"))
        self.actionNt_derived = QtGui.QAction(Trui)
        self.actionNt_derived.setCheckable(True)
        self.actionNt_derived.setObjectName(_fromUtf8("actionNt_derived"))
        self.actionFile2file_settings = QtGui.QAction(Trui)
        self.actionFile2file_settings.setObjectName(_fromUtf8("actionFile2file_settings"))
        self.action_local_GDAL = QtGui.QAction(Trui)
        self.action_local_GDAL.setCheckable(True)
        self.action_local_GDAL.setObjectName(_fromUtf8("action_local_GDAL"))
        self.action_own_GDAL = QtGui.QAction(Trui)
        self.action_own_GDAL.setCheckable(True)
        self.action_own_GDAL.setObjectName(_fromUtf8("action_own_GDAL"))
        self.actionGDAL_settings = QtGui.QAction(Trui)
        self.actionGDAL_settings.setObjectName(_fromUtf8("actionGDAL_settings"))
        self.menuHelp.addAction(self.actionHelp_local)
        self.menuHelp.addAction(self.actionAbout_KMSTrans)
        self.menuFile.addAction(self.actionNew_KMSTrans)
        self.menuFile.addAction(self.actionExit)
        self.menuRegion.addAction(self.actionDK)
        self.menuRegion.addAction(self.actionFO)
        self.menuRegion.addAction(self.actionGR)
        self.menuRegion.addAction(self.actionWorld)
        self.menuAngular_units.addAction(self.actionDegrees)
        self.menuAngular_units.addAction(self.actionRadians)
        self.menuAngular_units.addAction(self.actionSx)
        self.menuAngular_units.addAction(self.actionNt)
        self.menuAngular_units_derived_output.addAction(self.actionDegrees_derived)
        self.menuAngular_units_derived_output.addAction(self.actionRadians_derived)
        self.menuAngular_units_derived_output.addAction(self.actionSx_derived)
        self.menuAngular_units_derived_output.addAction(self.actionNt_derived)
        self.menuSettings.addAction(self.menuRegion.menuAction())
        self.menuSettings.addAction(self.menuAngular_units.menuAction())
        self.menuSettings.addAction(self.menuAngular_units_derived_output.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionGeoid_directory)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionFile2file_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionGDAL_settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Trui)
        self.main_tab_host.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionStation_names_in_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionStation_names_in_output.setChecked)
        QtCore.QObject.connect(self.actionStation_names_in_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionStation_names_in_output.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_f2f_ogr_driver.setEnabled)
        QtCore.QObject.connect(self.chb_f2f_label_in_file, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_f2f_input_system.setDisabled)
        QtCore.QObject.connect(self.chb_show_scale, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txt_scale.setEnabled)
        QtCore.QObject.connect(self.chb_show_scale, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txt_meridian_convergence.setEnabled)
        QtCore.QObject.connect(self.chb_f2f_use_log, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_f2f_log_name.setEnabled)
        QtCore.QObject.connect(self.bt_f2f_clear_log, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txt_f2f_log.clear)
        QtCore.QObject.connect(self.chb_f2f_use_log, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chb_f2f_verbose.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.bt_f2f_input_layers.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chb_f2f_all_layers.setEnabled)
        QtCore.QObject.connect(self.rdobt_f2f_ogr, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_f2f_layers_in.setEnabled)
        QtCore.QObject.connect(self.chb_f2f_all_layers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_f2f_layers_in.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Trui)

    def retranslateUi(self, Trui):
        Trui.setWindowTitle(_translate("Trui", "TRUI", None))
        Trui.setWhatsThis(_translate("Trui", "<html><head/><body><p>Main window</p></body></html>", None))
        self.lbl_current_geoid_directory.setText(_translate("Trui", "Current geoid directory:", None))
        self.lbl_geoid_dir_value.setText(_translate("Trui", "Geoid dir", None))
        self.lbl_region.setText(_translate("Trui", "Region:", None))
        self.lbl_region_value.setText(_translate("Trui", "Region", None))
        self.lbl_geo_coords.setText(_translate("Trui", "Geographic coordinates:", None))
        self.lbl_geo_coords_value.setText(_translate("Trui", "dg", None))
        self.lbl_input_info.setToolTip(_translate("Trui", "Input system description", None))
        self.lbl_input_info.setWhatsThis(_translate("Trui", "Detailed description of input srs.", None))
        self.lbl_input_info.setText(_translate("Trui", "Input system info:", None))
        self.lbl_output_info.setToolTip(_translate("Trui", "Output system description.", None))
        self.lbl_output_info.setWhatsThis(_translate("Trui", "Detailed description of output system.", None))
        self.lbl_output_info.setText(_translate("Trui", "Output system info:", None))
        self.lbl_input_system.setText(_translate("Trui", "Input system:  ", None))
        self.lbl_x_in.setText(_translate("Trui", "Easting:", None))
        self.lbl_y_in.setText(_translate("Trui", "Northing:", None))
        self.lbl_z_in.setText(_translate("Trui", "H:", None))
        self.cb_input_system.setToolTip(_translate("Trui", "Input minilabel", None))
        self.cb_input_system.setWhatsThis(_translate("Trui", "Specify input system minilabel here by selecting from dropdown list or typing one yourself. Enter triggers parsing and transformation.", None))
        self.bt_change_h_in.setText(_translate("Trui", "Change H", None))
        self.txt_x_in.setWhatsThis(_translate("Trui", "Input coordinate. Can contain units like dg, sx, nt, rad or m. Enter triggers a transformation.", None))
        self.txt_y_in.setWhatsThis(_translate("Trui", "Input coordinate. Can contain units like dg, sx, nt, rad or m. Enter triggers a transformation.", None))
        self.txt_z_in.setWhatsThis(_translate("Trui", "Input z-coordinate. Can contain unit (=m). Enter triggers a transformation.", None))
        self.txt_x_out.setWhatsThis(_translate("Trui", "Output coordinate. Can contain units like dg, sx, nt, rad or m. ", None))
        self.bt_change_h_out.setText(_translate("Trui", "Change H", None))
        self.txt_y_out.setWhatsThis(_translate("Trui", "Output coordinate. Can contain units like dg, sx, nt, rad or m. ", None))
        self.cb_output_system.setToolTip(_translate("Trui", "Output minilabel.", None))
        self.cb_output_system.setWhatsThis(_translate("Trui", "Specify output system minilabel here by selecting from dropdown list or typing one yourself. Enter triggers parsing and transformation.", None))
        self.txt_z_out.setWhatsThis(_translate("Trui", "Output z coordinate.", None))
        self.lbl_x_out.setText(_translate("Trui", "Easting:", None))
        self.lbl_z_out.setText(_translate("Trui", "H:", None))
        self.lbl_y_out.setText(_translate("Trui", "Northing:", None))
        self.lbl_output_system.setText(_translate("Trui", "Output system:", None))
        self.bt_interactive_swap.setWhatsThis(_translate("Trui", "Swap input/output", None))
        self.bt_interactive_swap.setText(_translate("Trui", "Swap input/output", None))
        self.bt_interactive_transform.setToolTip(_translate("Trui", "Trigger a transformation", None))
        self.bt_interactive_transform.setWhatsThis(_translate("Trui", "Trigger a transformation.", None))
        self.bt_interactive_transform.setText(_translate("Trui", "Transform", None))
        self.gv_map.setToolTip(_translate("Trui", "Map Window", None))
        self.gv_map.setWhatsThis(_translate("Trui", "<html><head/><body><p>Map window - geographic coordinates. Will show current location.</p></body></html>", None))
        self.bt_zoom_in.setText(_translate("Trui", "zoom in", None))
        self.bt_zoom_out.setText(_translate("Trui", "zoom out", None))
        self.chb_zoom_to_point.setToolTip(_translate("Trui", "Check to alwyas center on zoom.", None))
        self.chb_zoom_to_point.setWhatsThis(_translate("Trui", "Check this box to alwyas center current point on zoom.", None))
        self.chb_zoom_to_point.setText(_translate("Trui", "Zoom to point", None))
        self.lbl_geoid_height.setText(_translate("Trui", "Geoid height:", None))
        self.lbl_geoid_name.setText(_translate("Trui", "Geoid name:", None))
        self.txt_geoid_height.setWhatsThis(_translate("Trui", "Height of geoid above ellipsoid at current location.", None))
        self.txt_geoid_name.setWhatsThis(_translate("Trui", "Name of currently used geiod. ", None))
        self.chb_show_scale.setWhatsThis(_translate("Trui", "Show results of output system scale and convergence in text fields below.", None))
        self.chb_show_scale.setText(_translate("Trui", "Show output system scale and convergence.", None))
        self.lbl_scale.setText(_translate("Trui", "Scale:", None))
        self.lbl_meridian_convergence.setText(_translate("Trui", "Meridian convergence:", None))
        self.txt_scale.setWhatsThis(_translate("Trui", "Conformal scale factor of current output system at current location.", None))
        self.txt_meridian_convergence.setWhatsThis(_translate("Trui", "Meridian convergence of current output system at current location.", None))
        self.txt_log.setWhatsThis(_translate("Trui", "Text field for reporting things like error/log messages.", None))
        self.main_tab_host.setTabText(self.main_tab_host.indexOf(self.tab_interactive), _translate("Trui", "Interactive", None))
        self.tab_ogr.setWhatsThis(_translate("Trui", "<html><head/><body><p>Perform transformations between various datasources here.</p></body></html>", None))
        self.groupBox_5.setToolTip(_translate("Trui", "Select input \'driver\' here", None))
        self.groupBox_5.setWhatsThis(_translate("Trui", "Select input driver here...", None))
        self.groupBox_5.setTitle(_translate("Trui", "Driver / Format", None))
        self.rdobt_f2f_ogr.setText(_translate("Trui", "OGR", None))
        self.rdobt_f2f_simple_text.setText(_translate("Trui", "TEXT", None))
        self.rdobt_f2f_dsfl.setText(_translate("Trui", "DSFL", None))
        self.rdobt_f2f_kmsformat.setText(_translate("Trui", "KMSformat", None))
        self.groupBox_3.setTitle(_translate("Trui", "Source", None))
        self.lbl_f2f_input_file.setText(_translate("Trui", "Input path or connection string: ", None))
        self.txt_f2f_input_file.setWhatsThis(_translate("Trui", "<html><head/><body><p>A simple file name or, if using OGR, a connection string to e.g. a database. Use * wildcards for globbing over several input files in a directory.</p></body></html>", None))
        self.bt_f2f_browse_input.setText(_translate("Trui", "Browse files", None))
        self.bt_f2f_browse_input_dir.setText(_translate("Trui", "Browse dirs", None))
        self.chb_f2f_all_layers.setToolTip(_translate("Trui", "Check to transform all layers", None))
        self.chb_f2f_all_layers.setWhatsThis(_translate("Trui", "<html><head/><body><p>Generally (with OGR input), the batch process will iterate over all input layers, e.g. all shape files in a folder or all layers in a database. This behaviour can be changed by unchecking the check box an selecting specific input layers (as a ; separated list). </p></body></html>", None))
        self.chb_f2f_all_layers.setText(_translate("Trui", "Transform all layers, or specify layers here:", None))
        self.txt_f2f_layers_in.setToolTip(_translate("Trui", "Semicolon separated list of layers", None))
        self.txt_f2f_layers_in.setWhatsThis(_translate("Trui", "<html><head/><body><p>Specify input layers here, seperated by semicolons. Only valid for OGR input/output and formats that support layers, e.g. a directory of shape files or a FileGDB database.</p></body></html>", None))
        self.bt_f2f_input_layers.setText(_translate("Trui", "Select input layers", None))
        self.groupBox_4.setTitle(_translate("Trui", "Destination", None))
        self.lbl_f2f_ogrdriver.setText(_translate("Trui", "Output format will equal input format, except for OGR input driver, where output format can be chosen:", None))
        self.bt_f2f_creation_options.setToolTip(_translate("Trui", "Define OGR output driver creation options.", None))
        self.bt_f2f_creation_options.setWhatsThis(_translate("Trui", "Define OGR output driver creation options here. Refer to the OGR formats page (see help).", None))
        self.bt_f2f_creation_options.setText(_translate("Trui", "Creation options", None))
        self.lbl_f2f_output_file.setText(_translate("Trui", "Output path or connection string:", None))
        self.txt_f2f_output_file.setToolTip(_translate("Trui", "Output datasource or connection string.", None))
        self.txt_f2f_output_file.setWhatsThis(_translate("Trui", "Output datasource or connection string. If globbing over several input datasources (with * wildcards), the output datasource should be a directory.", None))
        self.bt_f2f_browse_output.setText(_translate("Trui", "Browse files", None))
        self.bt_f2f_browse_output_dir.setText(_translate("Trui", "Browse dirs", None))
        self.chb_f2f_use_log.setToolTip(_translate("Trui", "Use a log file to log errors and other output from TrLib.", None))
        self.chb_f2f_use_log.setWhatsThis(_translate("Trui", "Use a log file to log errors and other output from TrLib.", None))
        self.chb_f2f_use_log.setText(_translate("Trui", "Use log file", None))
        self.chb_f2f_verbose.setToolTip(_translate("Trui", "Turn on extra verbosity in logging.", None))
        self.chb_f2f_verbose.setWhatsThis(_translate("Trui", "Turn on extra verbosity in logging.", None))
        self.chb_f2f_verbose.setText(_translate("Trui", "Verbose output", None))
        self.txt_f2f_log_name.setToolTip(_translate("Trui", "File path for output log file.", None))
        self.txt_f2f_log_name.setWhatsThis(_translate("Trui", "File path for output log file.", None))
        self.bt_f2f_browse_log.setText(_translate("Trui", "Browse", None))
        self.groupBox_2.setTitle(_translate("Trui", "Transformation", None))
        self.lbl_f2f_input_info.setText(_translate("Trui", "TextLabel", None))
        self.lbl_f2f_output_info.setText(_translate("Trui", "TextLabel", None))
        self.chb_f2f_label_in_file.setToolTip(_translate("Trui", "Use this option if projection metadata is extractable from the input datasource.", None))
        self.chb_f2f_label_in_file.setWhatsThis(_translate("Trui", "Use this option if projection metadata is extractable from the input datasource.", None))
        self.chb_f2f_label_in_file.setText(_translate("Trui", "Label in file", None))
        self.chb_f2f_set_projection.setWhatsThis(_translate("Trui", "<html><head/><body><p>If checked, will attempt to write output projection metadata in destionation datasource.</p><p>This might fail for some OGR-drivers like e.g. \'FileGDB\', in which case the metadata can be attached via some appropriate tool afterwards, like e.g. ogr2ogr. </p></body></html>", None))
        self.chb_f2f_set_projection.setText(_translate("Trui", "Set output projection metadata in destination", None))
        self.label_3.setText(_translate("Trui", "Input system:", None))
        self.cb_f2f_input_system.setToolTip(_translate("Trui", "Specify input system", None))
        self.cb_f2f_input_system.setWhatsThis(_translate("Trui", "Specify an input spatial reference system as a minilabel, either by selecting from the dropdown list or simply typing one yourself (hit enter to try to parse it).", None))
        self.bt_f2f_change_h_in.setToolTip(_translate("Trui", "Change height system of input srs.", None))
        self.bt_f2f_change_h_in.setText(_translate("Trui", "Change H", None))
        self.label_5.setText(_translate("Trui", "Output system:", None))
        self.cb_f2f_output_system.setToolTip(_translate("Trui", "Specify output system", None))
        self.cb_f2f_output_system.setWhatsThis(_translate("Trui", "Specify an output spatial reference system as a minilabel, either by selecting from the dropdown list or simply typing one yourself (hit enter to try to parse it).", None))
        self.bt_f2f_change_h_out.setToolTip(_translate("Trui", "Change height system of input srs.", None))
        self.bt_f2f_change_h_out.setText(_translate("Trui", "Change H", None))
        self.txt_f2f_log.setWhatsThis(_translate("Trui", "Output log from batch transformation.", None))
        self.bt_f2f_execute.setToolTip(_translate("Trui", "Start the process.", None))
        self.bt_f2f_execute.setText(_translate("Trui", "Execute", None))
        self.bt_f2f_view_output.setToolTip(_translate("Trui", "View output.", None))
        self.bt_f2f_view_output.setWhatsThis(_translate("Trui", "View output (only applies to \'TEXT\' and \'KMS\' output).", None))
        self.bt_f2f_view_output.setText(_translate("Trui", "View output", None))
        self.bt_f2f_view_log.setToolTip(_translate("Trui", "View the log file.", None))
        self.bt_f2f_view_log.setWhatsThis(_translate("Trui", "View the log file (if used).", None))
        self.bt_f2f_view_log.setText(_translate("Trui", "View log file", None))
        self.bt_f2f_clear_log.setText(_translate("Trui", "Clear log window", None))
        self.bt_f2f_kill.setWhatsThis(_translate("Trui", "Kill the batch process if it seems to be stalled.", None))
        self.bt_f2f_kill.setText(_translate("Trui", "Kill process", None))
        self.bt_f2f_list_formats.setWhatsThis(_translate("Trui", "List available input and output formats for the batch transformation program.", None))
        self.bt_f2f_list_formats.setText(_translate("Trui", "list formats", None))
        self.main_tab_host.setTabText(self.main_tab_host.indexOf(self.tab_ogr), _translate("Trui", "Batch", None))
        self.menuHelp.setTitle(_translate("Trui", "Help", None))
        self.menuFile.setTitle(_translate("Trui", "File", None))
        self.menuSettings.setTitle(_translate("Trui", "Settings", None))
        self.menuRegion.setTitle(_translate("Trui", "Region", None))
        self.menuAngular_units.setTitle(_translate("Trui", "Units - geographic coordinates", None))
        self.menuAngular_units_derived_output.setTitle(_translate("Trui", "Angular units (derived output)", None))
        self.actionNew_KMSTrans.setText(_translate("Trui", "New window", None))
        self.actionAbout_KMSTrans.setText(_translate("Trui", "About ", None))
        self.actionHelp.setText(_translate("Trui", "Online help pages", None))
        self.actionHelp.setIconText(_translate("Trui", "www help page", None))
        self.actionDK.setText(_translate("Trui", "Denmark", None))
        self.actionFO.setText(_translate("Trui", "Faroe Islands", None))
        self.actionGR.setText(_translate("Trui", "Greenland", None))
        self.actionWorld.setText(_translate("Trui", "World", None))
        self.actionDegrees.setText(_translate("Trui", "degrees", None))
        self.actionRadians.setText(_translate("Trui", "radians", None))
        self.actionSx.setText(_translate("Trui", "sx: ddd mm ss.sss", None))
        self.actionNt.setText(_translate("Trui", "nt: ddd mm.mmmm", None))
        self.actionGeoid_directory.setText(_translate("Trui", "Geoid directory", None))
        self.actionStation_names_in_input.setText(_translate("Trui", "Station names in input", None))
        self.actionStation_names_in_output.setText(_translate("Trui", "Station names in output", None))
        self.actionVerbose_output.setText(_translate("Trui", "Verbose output", None))
        self.actionHelp_local.setText(_translate("Trui", "Local help pages", None))
        self.actionExit.setText(_translate("Trui", "Exit", None))
        self.actionDegrees_derived.setText(_translate("Trui", "degrees", None))
        self.actionRadians_derived.setText(_translate("Trui", "radians", None))
        self.actionSx_derived.setText(_translate("Trui", "sx: ddd mm ss.sss", None))
        self.actionNt_derived.setText(_translate("Trui", "nt: ddd mm.mmmm", None))
        self.actionFile2file_settings.setText(_translate("Trui", "TEXT/KMS format settings", None))
        self.action_local_GDAL.setText(_translate("Trui", "Use included GDAL", None))
        self.action_own_GDAL.setText(_translate("Trui", "Use own GDAL", None))
        self.actionGDAL_settings.setText(_translate("Trui", "GDAL settings", None))

